-- Optimized Structure for Fresh Installation (Template)
-- Generated by Antigravity

SET NAMES 'utf8mb4';
SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';

# Author: Eduard Laas
# Copyright © 2005 - 2026 SLAED
# License: GNU GPL 3
# Website: slaed.net
# Compatible: MySQL 8.0+ & MariaDB 10+

CREATE TABLE `{prefix}_admins` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `title` VARCHAR(50) DEFAULT NULL,
  `url` VARCHAR(255) NOT NULL DEFAULT '',
  `email` VARCHAR(255) NOT NULL,
  `pwd` VARCHAR(255) DEFAULT NULL,
  `super` BOOLEAN DEFAULT NULL,
  `editor` BOOLEAN DEFAULT NULL,
  `smail` BOOLEAN DEFAULT NULL,
  `modules` VARCHAR(255) NOT NULL DEFAULT '',
  `lang` VARCHAR(30) NOT NULL DEFAULT '',
  `ip` VARCHAR(45) NOT NULL DEFAULT '',
  `regdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastvisit` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  KEY `email` (`email`(191)),
  KEY `lastvisit` (`lastvisit`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_auto_links` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sitename` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NOT NULL DEFAULT '',
  `link` VARCHAR(100) NOT NULL,
  `mail` VARCHAR(100) NOT NULL,
  `hits` INT UNSIGNED NOT NULL DEFAULT 0,
  `outs` INT UNSIGNED NOT NULL DEFAULT 0,
  `added` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `added` (`added`),
  KEY `hits` (`hits`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_blocks` (
  `bid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bkey` VARCHAR(15) NOT NULL DEFAULT '',
  `title` VARCHAR(60) NOT NULL,
  `content` TEXT NOT NULL,
  `url` VARCHAR(200) NOT NULL DEFAULT '',
  `bposition` CHAR(1) NOT NULL DEFAULT '',
  `weight` SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  `active` BOOLEAN NOT NULL DEFAULT 1,
  `refresh` INT UNSIGNED NOT NULL DEFAULT 0,
  `time` VARCHAR(14) NOT NULL DEFAULT '0',
  `blanguage` VARCHAR(30) NOT NULL DEFAULT '',
  `blockfile` VARCHAR(255) NOT NULL DEFAULT '',
  `view` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `expire` VARCHAR(14) NOT NULL DEFAULT '0',
  `action` CHAR(1) NOT NULL DEFAULT '',
  `which` TEXT NOT NULL,
  PRIMARY KEY (`bid`),
  KEY `title` (`title`),
  KEY `active_position` (`active`, `bposition`),
  KEY `blanguage` (`blanguage`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `modul` VARCHAR(50) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `img` VARCHAR(100) NOT NULL DEFAULT '',
  `language` VARCHAR(30) NOT NULL DEFAULT '',
  `parentid` INT UNSIGNED NOT NULL DEFAULT 0,
  `cstatus` BOOLEAN NOT NULL DEFAULT 0,
  `ordern` INT UNSIGNED NOT NULL DEFAULT 0,
  `topics` INT UNSIGNED NOT NULL DEFAULT 0,
  `posts` INT UNSIGNED NOT NULL DEFAULT 0,
  `lpost_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `auth_view` VARCHAR(100) NOT NULL DEFAULT '',
  `auth_read` VARCHAR(100) NOT NULL DEFAULT '',
  `auth_post` VARCHAR(100) NOT NULL DEFAULT '',
  `auth_reply` VARCHAR(100) NOT NULL DEFAULT '',
  `auth_edit` VARCHAR(100) NOT NULL DEFAULT '',
  `auth_delete` VARCHAR(100) NOT NULL DEFAULT '',
  `auth_mod` VARCHAR(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `modul` (`modul`),
  KEY `parentid` (`parentid`),
  KEY `modul_lang_status` (`modul`, `language`, `cstatus`),
  KEY `ordern` (`ordern`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_clients` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_user` INT UNSIGNED NOT NULL DEFAULT 0,
  `id_product` INT UNSIGNED NOT NULL DEFAULT 0,
  `id_partner` INT UNSIGNED NOT NULL DEFAULT 0,
  `partner_proz` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `name` VARCHAR(255) NOT NULL,
  `adres` VARCHAR(255) NOT NULL DEFAULT '',
  `phone` VARCHAR(255) NOT NULL DEFAULT '',
  `email` VARCHAR(255) NOT NULL,
  `website` VARCHAR(255) NOT NULL DEFAULT '',
  `regdate` INT UNSIGNED NOT NULL DEFAULT 0,
  `enddate` INT UNSIGNED NOT NULL DEFAULT 0,
  `info` VARCHAR(255) NOT NULL DEFAULT '',
  `active` BOOLEAN DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `id_user` (`id_user`),
  KEY `id_product` (`id_product`),
  KEY `id_partner` (`id_partner`),
  KEY `active` (`active`),
  KEY `email` (`email`(191))
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cid` INT UNSIGNED NOT NULL DEFAULT 0,
  `modul` VARCHAR(60) NOT NULL,
  `date` DATETIME DEFAULT NULL,
  `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  `name` VARCHAR(25) NOT NULL,
  `host_name` VARCHAR(45) NOT NULL DEFAULT '',
  `comment` TEXT NOT NULL,
  `status` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `cid` (`cid`),
  KEY `uid` (`uid`),
  KEY `modul_status` (`modul`, `status`),
  KEY `date` (`date`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_content` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) DEFAULT NULL,
  `text` MEDIUMTEXT NOT NULL,
  `field` TEXT NOT NULL,
  `url` VARCHAR(200) NOT NULL,
  `time` DATETIME DEFAULT NULL,
  `refresh` INT UNSIGNED NOT NULL DEFAULT 0,
  `counter` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `counter` (`counter`),
  KEY `url` (`url`(191))
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_faq` (
  `fid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `catid` INT UNSIGNED NOT NULL DEFAULT 0,
  `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  `name` VARCHAR(25) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `time` DATETIME DEFAULT NULL,
  `hometext` TEXT,
  `comments` INT UNSIGNED NOT NULL DEFAULT 0,
  `counter` INT UNSIGNED NOT NULL DEFAULT 0,
  `ihome` BOOLEAN NOT NULL DEFAULT 0,
  `acomm` BOOLEAN NOT NULL DEFAULT 0,
  `score` INT UNSIGNED NOT NULL DEFAULT 0,
  `ratings` INT UNSIGNED NOT NULL DEFAULT 0,
  `ip_sender` VARCHAR(45) NOT NULL DEFAULT '',
  `status` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (`fid`),
  KEY `catid` (`catid`),
  KEY `counter` (`counter`),
  KEY `uid` (`uid`),
  KEY `status` (`status`),
  KEY `ihome` (`ihome`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_favorites` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  `fid` INT UNSIGNED NOT NULL DEFAULT 0,
  `modul` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `uid` (`uid`),
  KEY `fid` (`fid`),
  KEY `modul` (`modul`),
  UNIQUE KEY `uid_fid_modul` (`uid`, `fid`, `modul`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_files` (
  `lid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cid` INT UNSIGNED NOT NULL DEFAULT 0,
  `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  `name` VARCHAR(25) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `bodytext` TEXT NOT NULL,
  `url` VARCHAR(100) NOT NULL,
  `date` DATETIME DEFAULT NULL,
  `filesize` INT UNSIGNED NOT NULL DEFAULT 0,
  `version` VARCHAR(10) NOT NULL DEFAULT '',
  `email` VARCHAR(100) NOT NULL DEFAULT '',
  `homepage` VARCHAR(200) NOT NULL DEFAULT '',
  `ip_sender` VARCHAR(45) NOT NULL DEFAULT '',
  `counter` INT UNSIGNED NOT NULL DEFAULT 0,
  `ihome` BOOLEAN NOT NULL DEFAULT 0,
  `acomm` BOOLEAN NOT NULL DEFAULT 0,
  `votes` INT UNSIGNED NOT NULL DEFAULT 0,
  `totalvotes` INT UNSIGNED NOT NULL DEFAULT 0,
  `totalcomments` INT UNSIGNED NOT NULL DEFAULT 0,
  `hits` INT UNSIGNED NOT NULL DEFAULT 0,
  `status` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (`lid`),
  KEY `cid` (`cid`),
  KEY `title` (`title`),
  KEY `uid` (`uid`),
  KEY `status` (`status`),
  KEY `ihome` (`ihome`),
  KEY `counter` (`counter`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_forum` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pid` INT UNSIGNED NOT NULL DEFAULT 0,
  `catid` INT UNSIGNED NOT NULL DEFAULT 0,
  `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  `name` VARCHAR(25) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `time` DATETIME DEFAULT NULL,
  `hometext` TEXT,
  `field` TEXT NOT NULL,
  `comments` INT UNSIGNED DEFAULT 0,
  `counter` INT UNSIGNED NOT NULL DEFAULT 0,
  `score` INT UNSIGNED NOT NULL DEFAULT 0,
  `ratings` INT UNSIGNED NOT NULL DEFAULT 0,
  `ip_send` VARCHAR(45) NOT NULL DEFAULT '',
  `l_uid` INT UNSIGNED NOT NULL DEFAULT 0,
  `l_name` VARCHAR(25) NOT NULL DEFAULT '',
  `l_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `l_time` DATETIME DEFAULT NULL,
  `e_uid` INT UNSIGNED NOT NULL DEFAULT 0,
  `e_ip_send` VARCHAR(45) NOT NULL DEFAULT '',
  `e_time` DATETIME DEFAULT NULL,
  `status` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `pid` (`pid`),
  KEY `catid` (`catid`),
  KEY `counter` (`counter`),
  KEY `uid` (`uid`),
  KEY `status` (`status`),
  KEY `catid_status` (`catid`, `status`),
  KEY `time` (`time`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_groups` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `points` INT UNSIGNED NOT NULL DEFAULT 0,
  `extra` BOOLEAN NOT NULL DEFAULT 0,
  `rank` VARCHAR(255) NOT NULL DEFAULT '',
  `color` VARCHAR(7) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `name` (`name`(191))
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_help` (
  `sid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pid` INT UNSIGNED NOT NULL DEFAULT 0,
  `catid` INT UNSIGNED NOT NULL DEFAULT 0,
  `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  `aid` INT UNSIGNED NOT NULL DEFAULT 0,
  `title` VARCHAR(100) NOT NULL,
  `time` DATETIME DEFAULT NULL,
  `hometext` TEXT,
  `field` TEXT NOT NULL,
  `comments` INT UNSIGNED DEFAULT 0,
  `counter` INT UNSIGNED NOT NULL DEFAULT 0,
  `score` INT UNSIGNED NOT NULL DEFAULT 0,
  `ratings` INT UNSIGNED NOT NULL DEFAULT 0,
  `ip_sender` VARCHAR(45) NOT NULL DEFAULT '',
  `status` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (`sid`),
  KEY `pid` (`pid`),
  KEY `catid` (`catid`),
  KEY `counter` (`counter`),
  KEY `uid` (`uid`),
  KEY `status` (`status`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_jokes` (
  `jokeid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  `name` VARCHAR(25) NOT NULL,
  `date` DATETIME DEFAULT NULL,
  `title` VARCHAR(100) NOT NULL,
  `cat` INT UNSIGNED NOT NULL DEFAULT 0,
  `joke` TEXT NOT NULL,
  `rating` VARCHAR(100) NOT NULL DEFAULT '0',
  `ratingtot` VARCHAR(100) NOT NULL DEFAULT '0',
  `ip_sender` VARCHAR(45) NOT NULL DEFAULT '',
  `status` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (`jokeid`),
  KEY `cat` (`cat`),
  KEY `uid` (`uid`),
  KEY `status` (`status`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_links` (
  `lid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cid` INT UNSIGNED NOT NULL DEFAULT 0,
  `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  `name` VARCHAR(25) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `bodytext` TEXT NOT NULL,
  `url` VARCHAR(100) NOT NULL,
  `date` DATETIME DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL DEFAULT '',
  `ip_sender` VARCHAR(45) NOT NULL DEFAULT '',
  `counter` INT UNSIGNED NOT NULL DEFAULT 0,
  `ihome` BOOLEAN NOT NULL DEFAULT 0,
  `acomm` BOOLEAN NOT NULL DEFAULT 0,
  `votes` INT UNSIGNED NOT NULL DEFAULT 0,
  `totalvotes` INT UNSIGNED NOT NULL DEFAULT 0,
  `totalcomments` INT UNSIGNED NOT NULL DEFAULT 0,
  `hits` INT UNSIGNED NOT NULL DEFAULT 0,
  `status` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (`lid`),
  KEY `cid` (`cid`),
  KEY `title` (`title`),
  KEY `uid` (`uid`),
  KEY `status` (`status`),
  KEY `ihome` (`ihome`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_media` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cid` INT UNSIGNED NOT NULL DEFAULT 0,
  `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  `name` VARCHAR(25) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `subtitle` VARCHAR(100) NOT NULL DEFAULT '',
  `year` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `director` VARCHAR(100) NOT NULL DEFAULT '',
  `roles` VARCHAR(255) NOT NULL DEFAULT '',
  `description` TEXT NOT NULL,
  `createdby` VARCHAR(100) NOT NULL DEFAULT '',
  `duration` VARCHAR(100) NOT NULL DEFAULT '',
  `lang` VARCHAR(100) NOT NULL DEFAULT '',
  `note` TEXT NOT NULL,
  `format` VARCHAR(100) NOT NULL DEFAULT '',
  `quality` VARCHAR(100) NOT NULL DEFAULT '',
  `size` VARCHAR(100) NOT NULL DEFAULT '',
  `released` VARCHAR(100) NOT NULL DEFAULT '',
  `links` TEXT NOT NULL,
  `date` DATETIME DEFAULT NULL,
  `ihome` BOOLEAN NOT NULL DEFAULT 0,
  `acomm` BOOLEAN NOT NULL DEFAULT 0,
  `votes` INT UNSIGNED NOT NULL DEFAULT 0,
  `totalvotes` INT UNSIGNED NOT NULL DEFAULT 0,
  `totalcom` INT UNSIGNED NOT NULL DEFAULT 0,
  `hits` INT UNSIGNED NOT NULL DEFAULT 0,
  `ip_sender` VARCHAR(45) NOT NULL DEFAULT '',
  `status` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `cid` (`cid`),
  KEY `title` (`title`),
  KEY `uid` (`uid`),
  KEY `status` (`status`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_message` (
  `mid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `content` TEXT NOT NULL,
  `expire` INT UNSIGNED NOT NULL DEFAULT 0,
  `active` BOOLEAN NOT NULL DEFAULT 1,
  `view` BOOLEAN NOT NULL DEFAULT 1,
  `mlanguage` VARCHAR(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`mid`),
  KEY `active` (`active`),
  KEY `mlanguage` (`mlanguage`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_modules` (
  `mid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `active` BOOLEAN NOT NULL DEFAULT 0,
  `view` BOOLEAN NOT NULL DEFAULT 0,
  `inmenu` BOOLEAN NOT NULL DEFAULT 1,
  `mod_group` INT UNSIGNED DEFAULT 0,
  `blocks` BOOLEAN NOT NULL DEFAULT 0,
  `blocks_c` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (`mid`),
  KEY `title` (`title`),
  KEY `active` (`active`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_news` (
  `sid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `catid` INT UNSIGNED NOT NULL DEFAULT 0,
  `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  `name` VARCHAR(25) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `time` DATETIME DEFAULT NULL,
  `hometext` TEXT,
  `bodytext` TEXT NOT NULL,
  `field` TEXT NOT NULL,
  `vote` INT UNSIGNED NOT NULL DEFAULT 0,
  `comments` INT UNSIGNED DEFAULT 0,
  `counter` INT UNSIGNED NOT NULL DEFAULT 0,
  `ihome` BOOLEAN NOT NULL DEFAULT 0,
  `acomm` BOOLEAN NOT NULL DEFAULT 0,
  `score` INT UNSIGNED NOT NULL DEFAULT 0,
  `ratings` INT UNSIGNED NOT NULL DEFAULT 0,
  `associated` TEXT NOT NULL,
  `ip_sender` VARCHAR(45) NOT NULL DEFAULT '',
  `fix` BOOLEAN NOT NULL DEFAULT 0,
  `status` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (`sid`),
  KEY `catid` (`catid`),
  KEY `counter` (`counter`),
  KEY `uid` (`uid`),
  KEY `status` (`status`),
  KEY `ihome` (`ihome`),
  KEY `time` (`time`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_newsletter` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `content` TEXT,
  `mails` MEDIUMTEXT,
  `send` INT UNSIGNED NOT NULL DEFAULT 0,
  `time` DATETIME DEFAULT NULL,
  `endtime` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `time` (`time`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_order` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(255) NOT NULL,
  `info` TEXT NOT NULL,
  `com` TEXT NOT NULL,
  `ip` VARCHAR(45) NOT NULL DEFAULT '',
  `agent` VARCHAR(255) NOT NULL DEFAULT '',
  `date` DATETIME DEFAULT NULL,
  `status` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `status` (`status`),
  KEY `date` (`date`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_pages` (
  `pid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `catid` INT UNSIGNED NOT NULL DEFAULT 0,
  `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  `name` VARCHAR(25) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `time` DATETIME DEFAULT NULL,
  `hometext` TEXT,
  `bodytext` MEDIUMTEXT NOT NULL,
  `comments` INT UNSIGNED NOT NULL DEFAULT 0,
  `counter` INT UNSIGNED NOT NULL DEFAULT 0,
  `ihome` BOOLEAN NOT NULL DEFAULT 0,
  `acomm` BOOLEAN NOT NULL DEFAULT 0,
  `score` INT UNSIGNED NOT NULL DEFAULT 0,
  `ratings` INT UNSIGNED NOT NULL DEFAULT 0,
  `ip_sender` VARCHAR(45) NOT NULL DEFAULT '',
  `status` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (`pid`),
  KEY `catid` (`catid`),
  KEY `uid` (`uid`),
  KEY `status` (`status`),
  KEY `ihome` (`ihome`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_partners` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_user` INT UNSIGNED NOT NULL DEFAULT 0,
  `name` VARCHAR(255) NOT NULL,
  `adres` VARCHAR(255) NOT NULL DEFAULT '',
  `phone` VARCHAR(255) NOT NULL DEFAULT '',
  `email` VARCHAR(255) NOT NULL,
  `website` VARCHAR(255) NOT NULL DEFAULT '',
  `webmoney` VARCHAR(255) NOT NULL DEFAULT '',
  `paypal` VARCHAR(255) NOT NULL DEFAULT '',
  `regdate` INT UNSIGNED NOT NULL DEFAULT 0,
  `rest` INT UNSIGNED NOT NULL DEFAULT 0,
  `bek` INT UNSIGNED NOT NULL DEFAULT 0,
  `active` BOOLEAN DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `id_user` (`id_user`),
  KEY `active` (`active`),
  KEY `email` (`email`(191))
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_privat` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uidin` INT UNSIGNED NOT NULL DEFAULT 0,
  `uidout` INT UNSIGNED NOT NULL DEFAULT 0,
  `title` VARCHAR(100) NOT NULL,
  `content` TEXT NOT NULL,
  `date` DATETIME DEFAULT NULL,
  `ip_sender` VARCHAR(45) NOT NULL DEFAULT '',
  `status` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `uidin` (`uidin`),
  KEY `uidout` (`uidout`),
  KEY `status` (`status`),
  KEY `date` (`date`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_products` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cid` INT UNSIGNED NOT NULL DEFAULT 0,
  `time` DATETIME DEFAULT NULL,
  `title` VARCHAR(100) NOT NULL,
  `text` TEXT NOT NULL,
  `bodytext` TEXT NOT NULL,
  `preis` INT UNSIGNED NOT NULL DEFAULT 0,
  `vote` INT UNSIGNED NOT NULL DEFAULT 0,
  `assoc` TEXT NOT NULL,
  `ihome` BOOLEAN NOT NULL DEFAULT 0,
  `acomm` BOOLEAN NOT NULL DEFAULT 0,
  `com` INT UNSIGNED NOT NULL DEFAULT 0,
  `count` INT UNSIGNED NOT NULL DEFAULT 0,
  `votes` INT UNSIGNED NOT NULL DEFAULT 0,
  `totalvotes` INT UNSIGNED NOT NULL DEFAULT 0,
  `fix` BOOLEAN NOT NULL DEFAULT 0,
  `active` BOOLEAN DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `cid` (`cid`),
  KEY `active` (`active`),
  KEY `ihome` (`ihome`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_rating` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `mid` INT UNSIGNED NOT NULL DEFAULT 0,
  `modul` VARCHAR(50) NOT NULL,
  `time` VARCHAR(14) NOT NULL,
  `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  `host` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `mid` (`mid`),
  KEY `modul` (`modul`),
  KEY `uid` (`uid`),
  UNIQUE KEY `mid_modul_uid` (`mid`, `modul`, `uid`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_referer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uid` INT UNSIGNED NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  `ip` VARCHAR(45) NOT NULL DEFAULT '',
  `referer` VARCHAR(2048) NOT NULL DEFAULT '',
  `link` VARCHAR(2048) NOT NULL DEFAULT '',
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lid` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `uid` (`uid`),
  KEY `date` (`date`),
  KEY `ip` (`ip`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_search` (
  `sl_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sl_word` VARCHAR(255) NOT NULL,
  `sl_modul` VARCHAR(50) NOT NULL,
  `sl_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sl_score` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`sl_id`),
  KEY `sl_word` (`sl_word`(191)),
  KEY `sl_modul` (`sl_modul`),
  KEY `sl_time` (`sl_time`),
  KEY `sl_word_modul` (`sl_word`(191), `sl_modul`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_session` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uname` VARCHAR(40) NOT NULL,
  `time` BIGINT UNSIGNED NOT NULL,
  `host_addr` VARCHAR(45) NOT NULL DEFAULT '',
  `guest` BOOLEAN NOT NULL DEFAULT 0,
  `module` VARCHAR(25) NOT NULL DEFAULT '',
  `url` VARCHAR(2048) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `uname` (`uname`),
  KEY `time` (`time`),
  KEY `host_addr` (`host_addr`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(25) NOT NULL,
  `user_rank` VARCHAR(25) NOT NULL DEFAULT '',
  `user_email` VARCHAR(255) NOT NULL,
  `user_website` VARCHAR(255) NOT NULL DEFAULT '',
  `user_avatar` VARCHAR(255) NOT NULL DEFAULT '',
  `user_regdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_occ` VARCHAR(100) DEFAULT NULL,
  `user_from` VARCHAR(100) DEFAULT NULL,
  `user_interests` VARCHAR(150) NOT NULL DEFAULT '',
  `user_sig` VARCHAR(255) DEFAULT NULL,
  `user_viewemail` BOOLEAN DEFAULT NULL,
  `user_password` VARCHAR(255) NOT NULL,
  `user_storynum` TINYINT UNSIGNED NOT NULL DEFAULT 10,
  `user_blockon` BOOLEAN NOT NULL DEFAULT 0,
  `user_block` TEXT NOT NULL,
  `user_theme` VARCHAR(255) NOT NULL DEFAULT '',
  `user_newsletter` BOOLEAN NOT NULL DEFAULT 1,
  `user_fsmail` BOOLEAN NOT NULL DEFAULT 1,
  `user_psmail` BOOLEAN NOT NULL DEFAULT 1,
  `user_lastvisit` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_lang` VARCHAR(255) NOT NULL DEFAULT 'russian',
  `user_points` INT UNSIGNED DEFAULT 0,
  `user_last_ip` VARCHAR(45) NOT NULL DEFAULT '',
  `user_warnings` TEXT NOT NULL,
  `user_acess` BOOLEAN NOT NULL DEFAULT 0,
  `user_group` INT NOT NULL DEFAULT 0,
  `user_birthday` DATE DEFAULT NULL,
  `user_gender` BOOLEAN NOT NULL DEFAULT 0,
  `user_votes` INT UNSIGNED NOT NULL DEFAULT 0,
  `user_totalvotes` INT UNSIGNED NOT NULL DEFAULT 0,
  `user_field` TEXT NOT NULL,
  `user_agent` VARCHAR(255) NOT NULL DEFAULT '',
  `user_network` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `user_name` (`user_name`),
  KEY `user_email` (`user_email`(191)),
  KEY `user_group` (`user_group`),
  KEY `user_points` (`user_points`),
  KEY `user_lastvisit` (`user_lastvisit`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_users_temp` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(25) NOT NULL,
  `user_email` VARCHAR(255) NOT NULL,
  `user_password` VARCHAR(255) NOT NULL,
  `user_regdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `check_num` VARCHAR(50) NOT NULL,
  `time` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `user_name` (`user_name`),
  KEY `check_num` (`check_num`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_voting` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `modul` VARCHAR(50) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `questions` TEXT NOT NULL,
  `answer` TEXT NOT NULL,
  `date` DATETIME DEFAULT NULL,
  `enddate` DATETIME DEFAULT NULL,
  `multi` BOOLEAN NOT NULL DEFAULT 0,
  `comments` INT UNSIGNED NOT NULL DEFAULT 0,
  `language` VARCHAR(30) NOT NULL DEFAULT '',
  `acomm` BOOLEAN NOT NULL DEFAULT 0,
  `ip` VARCHAR(45) NOT NULL DEFAULT '',
  `typ` BOOLEAN NOT NULL DEFAULT 0,
  `status` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `modul` (`modul`),
  KEY `status` (`status`),
  KEY `language` (`language`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

SET FOREIGN_KEY_CHECKS = 1;
