# Author: Eduard Laas
# Copyright © 2005 - 2026 SLAED
# License: GNU GPL 3
# Website: slaed.net
# Compatible: MySQL 8.0+ & MariaDB 10+

SET SQL_MODE='TRADITIONAL';
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE `{prefix}_referer`;
CREATE TABLE `{prefix}_referer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uid` INT UNSIGNED NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  `ip` VARCHAR(45) NOT NULL DEFAULT '',
  `referer` VARCHAR(2048) NOT NULL DEFAULT '',
  `link` VARCHAR(2048) NOT NULL DEFAULT '',
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lid` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `uid` (`uid`),
  KEY `date` (`date`),
  KEY `ip` (`ip`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

DROP TABLE `{prefix}_session`;
CREATE TABLE `{prefix}_session` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uname` VARCHAR(40) NOT NULL,
  `time` BIGINT UNSIGNED NOT NULL,
  `host_addr` VARCHAR(45) NOT NULL DEFAULT '',
  `guest` BOOLEAN NOT NULL DEFAULT 0,
  `module` VARCHAR(25) NOT NULL DEFAULT '',
  `url` VARCHAR(2048) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `uname` (`uname`),
  KEY `time` (`time`),
  KEY `host_addr` (`host_addr`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

CREATE TABLE `{prefix}_search` (
  `sl_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sl_word` VARCHAR(255) NOT NULL,
  `sl_modul` VARCHAR(50) NOT NULL,
  `sl_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sl_score` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`sl_id`),
  KEY `sl_word` (`sl_word`(191)),
  KEY `sl_modul` (`sl_modul`),
  KEY `sl_time` (`sl_time`),
  KEY `sl_word_modul` (`sl_word`(191), `sl_modul`)
) ENGINE={engine} DEFAULT CHARSET={charset} COLLATE={collate};

UPDATE `{prefix}_auto_links` SET `added` = '1970-01-01 00:00:01' WHERE `added` = '0000-00-00 00:00:00' OR `added` IS NULL OR `added` < '1970-01-01 00:00:01';

ALTER TABLE `{prefix}_admins`
  MODIFY `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `title` VARCHAR(50) DEFAULT NULL,
  MODIFY `pwd` VARCHAR(255) DEFAULT NULL,
  MODIFY `super` BOOLEAN DEFAULT NULL,
  MODIFY `editor` BOOLEAN DEFAULT NULL,
  MODIFY `smail` BOOLEAN DEFAULT NULL,
  MODIFY `modules` VARCHAR(255) NOT NULL DEFAULT '',
  MODIFY `lang` VARCHAR(30) NOT NULL DEFAULT '',
  MODIFY `ip` VARCHAR(45) NOT NULL DEFAULT '',
  MODIFY `regdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY `lastvisit` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD UNIQUE KEY `name` (`name`),
  ADD KEY `email` (`email`(191)),
  ADD KEY `lastvisit` (`lastvisit`);

ALTER TABLE `{prefix}_auto_links`
  MODIFY `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `description` VARCHAR(255) NOT NULL DEFAULT '',
  MODIFY `hits` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `outs` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `added` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD KEY `added` (`added`),
  ADD KEY `hits` (`hits`);

ALTER TABLE `{prefix}_blocks`
  MODIFY `bid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `bkey` VARCHAR(15) NOT NULL DEFAULT '',
  MODIFY `url` VARCHAR(200) NOT NULL DEFAULT '',
  MODIFY `bposition` CHAR(1) NOT NULL DEFAULT '',
  MODIFY `weight` SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  MODIFY `active` BOOLEAN NOT NULL DEFAULT 1,
  MODIFY `refresh` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `blanguage` VARCHAR(30) NOT NULL DEFAULT '',
  MODIFY `blockfile` VARCHAR(255) NOT NULL DEFAULT '',
  MODIFY `view` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `action` CHAR(1) NOT NULL DEFAULT '',
  ADD KEY `active_position` (`active`, `bposition`),
  ADD KEY `blanguage` (`blanguage`);

ALTER TABLE `{prefix}_categories`
  MODIFY `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `img` VARCHAR(100) NOT NULL DEFAULT '',
  MODIFY `language` VARCHAR(30) NOT NULL DEFAULT '',
  MODIFY `parentid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `cstatus` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `ordern` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `topics` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `posts` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `lpost_id` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `auth_view` VARCHAR(100) NOT NULL DEFAULT '',
  MODIFY `auth_read` VARCHAR(100) NOT NULL DEFAULT '',
  MODIFY `auth_post` VARCHAR(100) NOT NULL DEFAULT '',
  MODIFY `auth_reply` VARCHAR(100) NOT NULL DEFAULT '',
  MODIFY `auth_edit` VARCHAR(100) NOT NULL DEFAULT '',
  MODIFY `auth_delete` VARCHAR(100) NOT NULL DEFAULT '',
  MODIFY `auth_mod` VARCHAR(100) NOT NULL DEFAULT '',
  ADD KEY `modul_lang_status` (`modul`, `language`, `cstatus`),
  ADD KEY `ordern` (`ordern`);

ALTER TABLE `{prefix}_clients`
  MODIFY `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `id_user` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `id_product` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `id_partner` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `partner_proz` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `adres` VARCHAR(255) NOT NULL DEFAULT '',
  MODIFY `phone` VARCHAR(255) NOT NULL DEFAULT '',
  MODIFY `website` VARCHAR(255) NOT NULL DEFAULT '',
  MODIFY `regdate` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `enddate` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `info` VARCHAR(255) NOT NULL DEFAULT '',
  MODIFY `active` BOOLEAN DEFAULT 0,
  ADD KEY `id_user` (`id_user`),
  ADD KEY `id_product` (`id_product`),
  ADD KEY `id_partner` (`id_partner`),
  ADD KEY `active` (`active`),
  ADD KEY `email` (`email`(191));

ALTER TABLE `{prefix}_comment`
  MODIFY `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `cid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `host_name` VARCHAR(45) NOT NULL DEFAULT '',
  MODIFY `status` BOOLEAN NOT NULL DEFAULT 0,
  ADD KEY `modul_status` (`modul`, `status`),
  ADD KEY `date` (`date`);

ALTER TABLE `{prefix}_content`
  MODIFY `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `refresh` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `counter` INT UNSIGNED NOT NULL DEFAULT 0,
  ADD KEY `url` (`url`(191));

ALTER TABLE `{prefix}_faq`
  MODIFY `fid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `catid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `comments` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `counter` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `ihome` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `acomm` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `score` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `ratings` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `ip_sender` VARCHAR(45) NOT NULL DEFAULT '',
  MODIFY `status` BOOLEAN NOT NULL DEFAULT 0,
  ADD KEY `uid` (`uid`),
  ADD KEY `status` (`status`),
  ADD KEY `ihome` (`ihome`);

ALTER TABLE `{prefix}_favorites`
  MODIFY `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `fid` INT UNSIGNED NOT NULL DEFAULT 0,
  ADD KEY `modul` (`modul`),
  ADD UNIQUE KEY `uid_fid_modul` (`uid`, `fid`, `modul`);

ALTER TABLE `{prefix}_files`
  MODIFY `lid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `cid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `filesize` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `version` VARCHAR(10) NOT NULL DEFAULT '',
  MODIFY `email` VARCHAR(100) NOT NULL DEFAULT '',
  MODIFY `homepage` VARCHAR(200) NOT NULL DEFAULT '',
  MODIFY `ip_sender` VARCHAR(45) NOT NULL DEFAULT '',
  MODIFY `counter` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `ihome` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `acomm` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `votes` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `totalvotes` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `totalcomments` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `hits` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `status` BOOLEAN NOT NULL DEFAULT 0,
  ADD KEY `uid` (`uid`),
  ADD KEY `status` (`status`),
  ADD KEY `ihome` (`ihome`),
  ADD KEY `counter` (`counter`);

ALTER TABLE `{prefix}_forum`
  MODIFY `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `pid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `catid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `comments` INT UNSIGNED DEFAULT 0,
  MODIFY `counter` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `score` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `ratings` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `ip_send` VARCHAR(45) NOT NULL DEFAULT '',
  MODIFY `l_uid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `l_name` VARCHAR(25) NOT NULL DEFAULT '',
  MODIFY `l_id` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `e_uid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `e_ip_send` VARCHAR(45) NOT NULL DEFAULT '',
  MODIFY `status` BOOLEAN NOT NULL DEFAULT 0,
  ADD KEY `uid` (`uid`),
  ADD KEY `status` (`status`),
  ADD KEY `catid_status` (`catid`, `status`),
  ADD KEY `time` (`time`);

ALTER TABLE `{prefix}_groups`
  MODIFY `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `points` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `extra` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `rank` VARCHAR(255) NOT NULL DEFAULT '',
  MODIFY `color` VARCHAR(7) NOT NULL DEFAULT '',
  ADD KEY `name` (`name`(191));

ALTER TABLE `{prefix}_help`
  MODIFY `sid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `pid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `catid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `aid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `comments` INT UNSIGNED DEFAULT 0,
  MODIFY `counter` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `score` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `ratings` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `ip_sender` VARCHAR(45) NOT NULL DEFAULT '',
  MODIFY `status` BOOLEAN NOT NULL DEFAULT 0,
  ADD KEY `uid` (`uid`),
  ADD KEY `status` (`status`);

ALTER TABLE `{prefix}_jokes`
  MODIFY `jokeid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `cat` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `ip_sender` VARCHAR(45) NOT NULL DEFAULT '',
  MODIFY `status` BOOLEAN NOT NULL DEFAULT 0,
  ADD KEY `uid` (`uid`),
  ADD KEY `status` (`status`);

ALTER TABLE `{prefix}_links`
  MODIFY `lid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `cid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `email` VARCHAR(100) NOT NULL DEFAULT '',
  MODIFY `ip_sender` VARCHAR(45) NOT NULL DEFAULT '',
  MODIFY `counter` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `ihome` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `acomm` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `votes` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `totalvotes` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `totalcomments` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `hits` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `status` BOOLEAN NOT NULL DEFAULT 0,
  ADD KEY `uid` (`uid`),
  ADD KEY `status` (`status`),
  ADD KEY `ihome` (`ihome`);

ALTER TABLE `{prefix}_media`
  MODIFY `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `cid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `subtitle` VARCHAR(100) NOT NULL DEFAULT '',
  MODIFY `year` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `director` VARCHAR(100) NOT NULL DEFAULT '',
  MODIFY `roles` VARCHAR(255) NOT NULL DEFAULT '',
  MODIFY `createdby` VARCHAR(100) NOT NULL DEFAULT '',
  MODIFY `duration` VARCHAR(100) NOT NULL DEFAULT '',
  MODIFY `lang` VARCHAR(100) NOT NULL DEFAULT '',
  MODIFY `format` VARCHAR(100) NOT NULL DEFAULT '',
  MODIFY `quality` VARCHAR(100) NOT NULL DEFAULT '',
  MODIFY `size` VARCHAR(100) NOT NULL DEFAULT '',
  MODIFY `released` VARCHAR(100) NOT NULL DEFAULT '',
  MODIFY `ihome` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `acomm` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `votes` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `totalvotes` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `totalcom` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `hits` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `ip_sender` VARCHAR(45) NOT NULL DEFAULT '',
  MODIFY `status` BOOLEAN NOT NULL DEFAULT 0,
  ADD KEY `uid` (`uid`),
  ADD KEY `status` (`status`);

ALTER TABLE `{prefix}_message`
  MODIFY `mid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `expire` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `active` BOOLEAN NOT NULL DEFAULT 1,
  MODIFY `view` BOOLEAN NOT NULL DEFAULT 1,
  MODIFY `mlanguage` VARCHAR(30) NOT NULL DEFAULT '',
  ADD KEY `active` (`active`),
  ADD KEY `mlanguage` (`mlanguage`);

ALTER TABLE `{prefix}_modules`
  MODIFY `mid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `active` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `view` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `inmenu` BOOLEAN NOT NULL DEFAULT 1,
  MODIFY `mod_group` INT UNSIGNED DEFAULT 0,
  MODIFY `blocks` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `blocks_c` BOOLEAN NOT NULL DEFAULT 0,
  ADD KEY `active` (`active`);

ALTER TABLE `{prefix}_news`
  MODIFY `sid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `catid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `vote` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `comments` INT UNSIGNED DEFAULT 0,
  MODIFY `counter` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `ihome` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `acomm` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `score` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `ratings` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `ip_sender` VARCHAR(45) NOT NULL DEFAULT '',
  MODIFY `fix` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `status` BOOLEAN NOT NULL DEFAULT 0,
  ADD KEY `uid` (`uid`),
  ADD KEY `status` (`status`),
  ADD KEY `ihome` (`ihome`),
  ADD KEY `time` (`time`);

ALTER TABLE `{prefix}_newsletter`
  MODIFY `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `send` INT UNSIGNED NOT NULL DEFAULT 0,
  ADD KEY `time` (`time`);

ALTER TABLE `{prefix}_order`
  MODIFY `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `ip` VARCHAR(45) NOT NULL DEFAULT '',
  MODIFY `agent` VARCHAR(255) NOT NULL DEFAULT '',
  MODIFY `status` BOOLEAN NOT NULL DEFAULT 0,
  ADD KEY `status` (`status`),
  ADD KEY `date` (`date`);

ALTER TABLE `{prefix}_pages`
  MODIFY `pid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `catid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `comments` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `counter` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `ihome` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `acomm` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `score` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `ratings` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `ip_sender` VARCHAR(45) NOT NULL DEFAULT '',
  MODIFY `status` BOOLEAN NOT NULL DEFAULT 0,
  ADD KEY `uid` (`uid`),
  ADD KEY `status` (`status`),
  ADD KEY `ihome` (`ihome`);

ALTER TABLE `{prefix}_partners`
  MODIFY `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `id_user` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `adres` VARCHAR(255) NOT NULL DEFAULT '',
  MODIFY `phone` VARCHAR(255) NOT NULL DEFAULT '',
  MODIFY `website` VARCHAR(255) NOT NULL DEFAULT '',
  MODIFY `webmoney` VARCHAR(255) NOT NULL DEFAULT '',
  MODIFY `paypal` VARCHAR(255) NOT NULL DEFAULT '',
  MODIFY `regdate` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `rest` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `bek` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `active` BOOLEAN DEFAULT 0,
  ADD KEY `id_user` (`id_user`),
  ADD KEY `active` (`active`),
  ADD KEY `email` (`email`(191));

ALTER TABLE `{prefix}_privat`
  MODIFY `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `uidin` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `uidout` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `ip_sender` VARCHAR(45) NOT NULL DEFAULT '',
  MODIFY `status` BOOLEAN NOT NULL DEFAULT 0,
  ADD KEY `uidin` (`uidin`),
  ADD KEY `uidout` (`uidout`),
  ADD KEY `status` (`status`),
  ADD KEY `date` (`date`);

ALTER TABLE `{prefix}_products`
  MODIFY `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `cid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `preis` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `vote` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `ihome` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `acomm` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `com` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `count` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `votes` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `totalvotes` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `fix` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `active` BOOLEAN DEFAULT 0,
  ADD KEY `cid` (`cid`),
  ADD KEY `active` (`active`),
  ADD KEY `ihome` (`ihome`);

ALTER TABLE `{prefix}_rating`
  MODIFY `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `mid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `host` VARCHAR(45) NOT NULL DEFAULT '',
  ADD KEY `uid` (`uid`),
  ADD UNIQUE KEY `mid_modul_uid` (`mid`, `modul`, `uid`);

UPDATE `{prefix}_users` SET `user_points` = 0 WHERE `user_points` < 0;
ALTER TABLE `{prefix}_users`
  MODIFY `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `user_rank` VARCHAR(25) NOT NULL DEFAULT '',
  MODIFY `user_website` VARCHAR(255) NOT NULL DEFAULT '',
  MODIFY `user_avatar` VARCHAR(255) NOT NULL DEFAULT '',
  MODIFY `user_regdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY `user_interests` VARCHAR(150) NOT NULL DEFAULT '',
  MODIFY `user_viewemail` BOOLEAN DEFAULT NULL,
  MODIFY `user_password` VARCHAR(255) NOT NULL,
  MODIFY `user_storynum` TINYINT UNSIGNED NOT NULL DEFAULT 10,
  MODIFY `user_blockon` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `user_theme` VARCHAR(255) NOT NULL DEFAULT '',
  MODIFY `user_newsletter` BOOLEAN NOT NULL DEFAULT 1,
  MODIFY `user_fsmail` BOOLEAN NOT NULL DEFAULT 1,
  MODIFY `user_psmail` BOOLEAN NOT NULL DEFAULT 1,
  MODIFY `user_lastvisit` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY `user_points` INT UNSIGNED DEFAULT 0,
  MODIFY `user_last_ip` VARCHAR(45) NOT NULL DEFAULT '',
  MODIFY `user_acess` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `user_group` INT NOT NULL DEFAULT 0,
  MODIFY `user_gender` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `user_votes` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `user_totalvotes` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `user_agent` VARCHAR(255) NOT NULL DEFAULT '',
  MODIFY `user_network` VARCHAR(255) NOT NULL DEFAULT '',
  ADD UNIQUE KEY `user_name` (`user_name`),
  ADD KEY `user_email` (`user_email`(191)),
  ADD KEY `user_group` (`user_group`),
  ADD KEY `user_points` (`user_points`),
  ADD KEY `user_lastvisit` (`user_lastvisit`);

ALTER TABLE `{prefix}_users_temp`
  MODIFY `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `user_password` VARCHAR(255) NOT NULL,
  MODIFY `user_regdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD UNIQUE KEY `user_name` (`user_name`),
  ADD KEY `check_num` (`check_num`);

ALTER TABLE `{prefix}_voting`
  MODIFY `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY `multi` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `comments` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `language` VARCHAR(30) NOT NULL DEFAULT '',
  MODIFY `acomm` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `ip` VARCHAR(45) NOT NULL DEFAULT '',
  MODIFY `typ` BOOLEAN NOT NULL DEFAULT 0,
  MODIFY `status` BOOLEAN NOT NULL DEFAULT 0,
  ADD KEY `status` (`status`),
  ADD KEY `language` (`language`);

SET FOREIGN_KEY_CHECKS=1;

ANALYZE TABLE `{prefix}_admins`;
ANALYZE TABLE `{prefix}_auto_links`;
ANALYZE TABLE `{prefix}_blocks`;
ANALYZE TABLE `{prefix}_categories`;
ANALYZE TABLE `{prefix}_clients`;
ANALYZE TABLE `{prefix}_comment`;
ANALYZE TABLE `{prefix}_content`;
ANALYZE TABLE `{prefix}_faq`;
ANALYZE TABLE `{prefix}_favorites`;
ANALYZE TABLE `{prefix}_files`;
ANALYZE TABLE `{prefix}_forum`;
ANALYZE TABLE `{prefix}_groups`;
ANALYZE TABLE `{prefix}_help`;
ANALYZE TABLE `{prefix}_jokes`;
ANALYZE TABLE `{prefix}_links`;
ANALYZE TABLE `{prefix}_media`;
ANALYZE TABLE `{prefix}_message`;
ANALYZE TABLE `{prefix}_modules`;
ANALYZE TABLE `{prefix}_news`;
ANALYZE TABLE `{prefix}_newsletter`;
ANALYZE TABLE `{prefix}_order`;
ANALYZE TABLE `{prefix}_pages`;
ANALYZE TABLE `{prefix}_partners`;
ANALYZE TABLE `{prefix}_privat`;
ANALYZE TABLE `{prefix}_products`;
ANALYZE TABLE `{prefix}_rating`;
ANALYZE TABLE `{prefix}_users`;
ANALYZE TABLE `{prefix}_users_temp`;
ANALYZE TABLE `{prefix}_voting`;