<?php
# Author: Eduard Laas
# Copyright © 2005 - 2025 SLAED
# License: GNU GPL 3
# Website: slaed.net

if (!defined('FUNC_FILE')) die('Illegal file access');

$conf = array (
  'adesc' => '1',
  'admcol' => '5',
  'admin_c' => 'panel',
  'adminfo' => '1',
  'admininfo' => 'Информация, которая будет доступна всем авторам. Отображение данной информации производится в верхней части панели администратора системы.',
  'adminmail' => 'slaedpro@mail.ru',
  'akeys' => '1',
  'alang' => '0',
  'amod' => 'news',
  'asearch' => '0',
  'bots' => 'AdsBot-Google=AdsBot Google,Aport Catalog Robot=Aport Catalog Bot,Aport=Aport Bot,AportCatalogRobot/2.0=Aport Catalog Bot,archive_org=Archive.org Bot,Ask Jeeves=Ask Jeeves Bot,AutoLuba/1.0=Yandex-MNT Bot,Baiduspider+=Baidu Spider,Begun Robot=Begun Bot,BlogPulse=BlogPulse Bot,booch=Booch Bot,CazoodleBot/=CazoodleBot,Crawler=SEO Crawler,FeedBurner/=FeedBurner,Feedfetcher-Google=Google Feedfetcher,FeedValidator=FeedValidator,GetSmart=Get Smart Bot,GigaBlast=Gigablast Bot,Gigabot/=Gigabot Bot,Google Desktop=Google Desktop,Googlebot=Google Bot,Googlebot-Image/=Google Image Bot,grub-client=Grub Client Bot,ia_archiver=IA.Archiver Bot,igdeSpyder=Igde Bot,Jetbot=Jet Bot,libwww=Punto Bot,libwww-perl/=Rambler Feed,liveinternet spider=Liveinternet Bot,Lycos=Lycos Bot,Mail.Ru=Mail.Ru Bot,Mediapartners-Google=Google Adsense Bot,MJ12bot/=Majestic-12 Bot,MLBot=MLBot,MnoGoSearch=Mno Go Search Bot,msnbot/=MSN Bot,msnbot-media/=MSNbot Media,msnbot-NewsBlogs/=MSN NewsBlogs,msnbot-webmaster/=Live Bot,NaverBot=Naver Bot,oBot=oBot,OOZBOT/=Setooz Bot,Openbot=Openfind Bot,psbot/=Psbot,Rambler=Rambler Bot,Scooter/=Alta Vista Bot,slurp@inktomi=Hot Bot,Speedy Spider=Speedy Spider,StackRambler=Stack Rambler Bot,TurnitinBot=Turnitin Bot,TurtleScanner=Turtle Scanner Bot,Twiceler-0.9=Cuill Bot,VadixBot=VadixBot Bot,Validome XML-Validator=Validome XML-Validator,Vampire=Net Vampire Bot,W3 SiteSearch Crawler=W3 Sitesearch,W3C_CSS_Validator_JFouffa/=W3C CSS Validator,W3C_Validator/=W3C Validator,W3C-checklink/=W3C Link Checker,WebAlta Crawler/=WebAlta Bot,WebCrawler=Fast Bot,Web-sniffer/=Web-sniffer,WebZIP=WebZIP Bot,WhatUSeek=What You Seek Bot,www.cys.ru=CYS Bot,XML Sitemaps Generator=XML Sitemaps Generator,YaDirectBot/=Yandex Direct,Yahoo! Slurp=Yahoo Bot,Yahoo!=Yahoo Bot,YahooFeedSeeker/=YahooSeeker Bot,Yahoo-MMCrawler/=Yahoo MMCrawler Bot,Yandex=Yandex Bot,YandexBlog/=YandexBlog Bot,Yanga WorldSearch Bot=Yanga WorldSearch Bot,ZipppBot=Zippp Bot',
  'botsact' => '1',
  'cache' => '0',
  'cache_b' => '0',
  'cache_c' => '0',
  'cache_css' => '0',
  'cache_d' => '7',
  'cache_script' => '0',
  'cache_t' => '600',
  'capkey' => '6Lc7qf8cAAAAAOPyBdjLMe_3AaO9kPSVqQzZQ0nI',
  'capsec' => '6Lc7qf8cAAAAAJ_X0LuY2FFJziwWWDnuNd3g-nR9',
  'censor' => '1',
  'censor_l' => 'antislaed,netlevel,sunvas',
  'censor_r' => '***',
  'clickable' => '0',
  'close' => '0',
  'css_c' => '0',
  'css_e' => '0',
  'css_f' => 'templates/[theme]/,plugins/jquery/ui/,plugins/fancybox/,plugins/uploadify/,plugins/syntaxhighlighter/styles/',
  'css_h' => '0',
  'db_t' => '1',
  'dbsync' => '0',
  'defis' => '-',
  'dkeys' => 'quot,amp,вам,вас,все,всех,где,даже,для,его,ей,если,есть,еще,её,и,или,их,как,когда,кого,кто,лишь,мне,мы,на,надо,нас,нет,но,он,она,они,оно,при,раз,так,уже,чем,что,эта,этих,это',
  'dletter' => '160',
  'fbots' => '21.by,a-counter.com.ua,about.com,acoon.com,aeiwi.com,all.by,alltheweb.com,altavista.com,amfibi.com,aolsearch.aol.com,aport.ru,ask.com,atlasua.net,ay.com.ua,baidu.com,belarusinfo.by,bigmir.net,bing.com,br.by,britannica.com,catalog.bel.biz,catalog.svich.com,codavr.ru,date.bs,dmoz.org,dogpile.com,entireweb.com,euroseek.net,exactseek.com,exalead.frsearch,excite.com,filesearch.ru,gala.net,gde.ru,genon.ru,gigablast.com,google.com,google.com.ua,google.de,google.net,google.ru,gugle.by,holmes.adamant.ua,hotbot.com,imhalal.com,info.com,infospace.com,ixquick.com,km.ru,links2go.com,list.np.by,liveinternet.ru,looksmart.com,lycos.com,lycos.ru,mail.ru,mamma.com,meta.ua,metabot.ru,metacrawler.com,minskin.net,myahint.com,mysearch.com,myway.com,najdivse.com,netoteka.ru,netsearch.org,nigma.ru,nol9.ru,online.ua,open.by,pepesearch.com,qango.com,qs.kiev.ua,rambler.ru,ru.yahoo.com,scrubtheweb.com,search.aol.com,search.com,search.com.ua,search.msn.com,search.yippy.com,searchking.com,sova.com.ua,teoma.com,tinEye.com,tit.by,tut.by,ualist.com,uaport.net,uaportal.com,ukrbiznes.com,ukrweb.com.ua,url.by,usluga.by,walhello.info,webalta.ru,webcrawler.com,websearch.com,webwombat.com.au,wisenut.com,ya.ru,yahoo.com,yandex.ru,zoneru.org,zubr.com',
  'flags' => '1',
  'forum' => '0',
  'forum_link' => 'http://0',
  'forum_mess' => 'http://0',
  'geo_ip' => '1',
  'gfx_chk' => '6',
  'gtime' => 'Europe/Berlin',
  'homeurl' => 'https://slaed.loc',
  'ip_link' => 'https://whatismyipaddress.com/ip/',
  'keys' => 'slaed,php,html5,css3,jquery,ajax,modul,pro,news,cms,web',
  'kletter' => '3',
  'kmix' => '0',
  'ksep' => '0',
  'kwords' => '15',
  'language' => 'german',
  'lic_f' => 'IFNMQUVELiBBbGwgcmlnaHRzIHJlc2VydmVkLg==',
  'lic_h' => 'UG93ZXJlZCBieSA8YSBocmVmPSJodHRwczovL3NsYWVkLm5ldCIgdGFyZ2V0PSJfYmxhbmsiIHRpdGxlPSJTTEFFRCBDTVMiPlNMQUVEIENNUzwvYT4gJmNvcHk7IDIwMDUt',
  'ltitle' => '1',
  'message' => '1',
  'module' => '0',
  'mtemp' => 'Здравствуйте!

[text]

С наилучшими пожеланиями,

SLAED CMS - Support
https://slaed.net
support@slaed.net',
  'multilingual' => '1',
  'newsletter' => '0',
  'newslettercount' => '4',
  'quality' => '4',
  'redaktor' => '1',
  'rewrite' => '0',
  'sblock' => '1',
  'script_a' => '0',
  'script_b' => '0',
  'script_c' => '0',
  'script_f' => 'plugins/system/global-func.js,plugins/jquery/jquery.js,plugins/jquery/ui/jquery-ui.js,plugins/jquery/jquery.tablesorter.js,plugins/jquery/jquery.cookie.js,plugins/fancybox/jquery.mousewheel.js,plugins/fancybox/jquery.fancybox.js,plugins/jquery/jquery.slaed.js',
  'script_h' => '0',
  'search' => '0',
  'sep' => '-',
  'sess_t' => '900',
  'session' => '1',
  'site_logo' => 'slaed_logo_256x340.png',
  'sitekey' => 'nGe80f3qVyHF7biIWwgx2VL3V',
  'sitename' => 'Название сайта',
  'slet' => '3',
  'slogan' => 'SLAED CMS - Content Management System. Современная система управления содержимым динамичных сайтов и мощная система управления интернет-порталами.',
  'snum' => '25',
  'snump' => '5',
  'startdate' => '2013-06-17 00:00:00',
  'syntax' => '2',
  'theme' => 'lite',
  'user_c' => 'slaed',
  'user_c_t' => '2592000',
  'var_view' => '1',
  'variables' => ',,,,,,,,',
  'version' => '6.3.0 Phoenix',
);