<?php
# Author: Eduard Laas
# 2005 - 2026 SLAED
# License: MIT
# Website: slaed.net

return [
    'fields' => [
        'account' => [
            'field1' => [
                'title' => 'Версия системы',
                'intro' => '',
                'type' => 'select',
                'default' => '',
                'options' => [
                    'items' => [
                        'option1' => [
                            'title' => 'SLAED CMS 1.6 Free',
                            'active' => true,
                            'sort' => 10,
                        ],
                        'option2' => [
                            'title' => 'SLAED CMS 5.* Pro',
                            'active' => true,
                            'sort' => 20,
                        ],
                        'option3' => [
                            'title' => 'Open SLAED 1.*',
                            'active' => true,
                            'sort' => 30,
                        ],
                        'option4' => [
                            'title' => 'SLAED CMS 4.* Pro',
                            'active' => true,
                            'sort' => 40,
                        ],
                        'option5' => [
                            'title' => 'SLAED CMS 2.6 Lite',
                            'active' => true,
                            'sort' => 50,
                        ],
                        'option6' => [
                            'title' => 'SLAED CMS 6.* Pro',
                            'active' => true,
                            'sort' => 60,
                        ],
                        'option7' => [
                            'title' => 'SLAED CMS 3.5 Pro',
                            'active' => true,
                            'sort' => 70,
                        ],
                        'option8' => [
                            'title' => 'SLAED CMS 2.5 Lite',
                            'active' => true,
                            'sort' => 80,
                        ],
                        'option9' => [
                            'title' => 'SLAED CMS 2.0 Pro',
                            'active' => true,
                            'sort' => 90,
                        ],
                        'option10' => [
                            'title' => 'SLAED CMS 3.0 Pro',
                            'active' => true,
                            'sort' => 100,
                        ],
                        'option11' => [
                            'title' => 'SLAED CMS 3.4 Pro',
                            'active' => true,
                            'sort' => 110,
                        ],
                        'option12' => [
                            'title' => 'SLAED CMS 2.4 Lite',
                            'active' => true,
                            'sort' => 120,
                        ],
                        'option13' => [
                            'title' => 'SLAED CMS 4 Pro',
                            'active' => true,
                            'sort' => 130,
                        ],
                        'option14' => [
                            'title' => 'SLAED CMS 3.3 Pro',
                            'active' => true,
                            'sort' => 140,
                        ],
                    ],
                ],
                'req' => false,
                'multi' => false,
                'active' => true,
                'sort' => 10,
            ],
            'field2' => [
                'title' => 'Ваше имя',
                'intro' => '',
                'type' => 'text',
                'default' => 'Андрей',
                'options' => [
                ],
                'req' => false,
                'multi' => false,
                'active' => true,
                'sort' => 20,
            ],
            'field3' => [
                'title' => 'Ваше мыло',
                'intro' => '',
                'type' => 'text',
                'default' => 'email@domain.net',
                'options' => [
                ],
                'req' => true,
                'multi' => false,
                'active' => true,
                'sort' => 30,
            ],
        ],
        'forum' => [
            'field1' => [
                'title' => 'Версия системы',
                'intro' => '',
                'type' => 'select',
                'default' => '',
                'options' => [
                    'items' => [
                        'option1' => [
                            'title' => 'Open SLAED 1.*',
                            'active' => true,
                            'sort' => 10,
                        ],
                        'option2' => [
                            'title' => 'SLAED CMS 2.6 Lite',
                            'active' => true,
                            'sort' => 20,
                        ],
                        'option3' => [
                            'title' => 'SLAED CMS 4.2 Pro',
                            'active' => true,
                            'sort' => 30,
                        ],
                        'option4' => [
                            'title' => 'SLAED CMS 6.* Pro',
                            'active' => true,
                            'sort' => 40,
                        ],
                        'option5' => [
                            'title' => 'SLAED CMS 5.* Pro',
                            'active' => true,
                            'sort' => 50,
                        ],
                        'option6' => [
                            'title' => 'SLAED CMS 4.* Pro',
                            'active' => true,
                            'sort' => 60,
                        ],
                        'option7' => [
                            'title' => 'SLAED CMS 3.5 Pro',
                            'active' => true,
                            'sort' => 70,
                        ],
                        'option8' => [
                            'title' => 'SLAED CMS 4.1 Pro',
                            'active' => true,
                            'sort' => 80,
                        ],
                        'option9' => [
                            'title' => 'SLAED CMS 1.6 Free',
                            'active' => true,
                            'sort' => 90,
                        ],
                        'option10' => [
                            'title' => 'SLAED CMS 2.5 Lite',
                            'active' => true,
                            'sort' => 100,
                        ],
                        'option11' => [
                            'title' => 'SLAED CMS 6.3 Pro',
                            'active' => true,
                            'sort' => 110,
                        ],
                        'option12' => [
                            'title' => 'SLAED CMS 6.0 - 6.2 Pro',
                            'active' => true,
                            'sort' => 120,
                        ],
                        'option13' => [
                            'title' => 'SLAED CMS 3.3 Pro',
                            'active' => true,
                            'sort' => 130,
                        ],
                        'option14' => [
                            'title' => 'SLAED CMS 2.4 Lite',
                            'active' => true,
                            'sort' => 140,
                        ],
                    ],
                ],
                'req' => false,
                'multi' => false,
                'active' => true,
                'sort' => 10,
            ],
            'field2' => [
                'title' => 'Версия PHP',
                'intro' => '',
                'type' => 'select',
                'default' => '',
                'options' => [
                    'items' => [
                        'option1' => [
                            'title' => 'PHP 5',
                            'active' => true,
                            'sort' => 10,
                        ],
                        'option2' => [
                            'title' => 'PHP 4',
                            'active' => true,
                            'sort' => 20,
                        ],
                        'option3' => [
                            'title' => '5',
                            'active' => true,
                            'sort' => 30,
                        ],
                        'option4' => [
                            'title' => '7',
                            'active' => true,
                            'sort' => 40,
                        ],
                        'option5' => [
                            'title' => '4',
                            'active' => true,
                            'sort' => 50,
                        ],
                    ],
                ],
                'req' => false,
                'multi' => false,
                'active' => true,
                'sort' => 20,
            ],
            'field3' => [
                'title' => 'Сервер',
                'intro' => '',
                'type' => 'select',
                'default' => '',
                'options' => [
                    'items' => [
                        'option1' => [
                            'title' => 'Сервер в интернете',
                            'active' => true,
                            'sort' => 10,
                        ],
                        'option2' => [
                            'title' => 'Локальный сервер',
                            'active' => true,
                            'sort' => 20,
                        ],
                    ],
                ],
                'req' => false,
                'multi' => false,
                'active' => true,
                'sort' => 30,
            ],
        ],
        'order' => [
            'field1' => [
                'title' => 'WebMoney',
                'intro' => '',
                'type' => 'text',
                'default' => '',
                'options' => [
                ],
                'req' => true,
                'multi' => false,
                'active' => true,
                'sort' => 10,
            ],
            'field2' => [
                'title' => 'Имя',
                'intro' => '',
                'type' => 'text',
                'default' => '',
                'options' => [
                ],
                'req' => false,
                'multi' => false,
                'active' => true,
                'sort' => 20,
            ],
            'field3' => [
                'title' => 'Фамилия',
                'intro' => '',
                'type' => 'text',
                'default' => '',
                'options' => [
                ],
                'req' => false,
                'multi' => false,
                'active' => true,
                'sort' => 30,
            ],
            'field4' => [
                'title' => 'Улица',
                'intro' => '',
                'type' => 'text',
                'default' => '',
                'options' => [
                ],
                'req' => false,
                'multi' => false,
                'active' => true,
                'sort' => 40,
            ],
            'field5' => [
                'title' => 'Индекс',
                'intro' => '',
                'type' => 'text',
                'default' => '',
                'options' => [
                ],
                'req' => false,
                'multi' => false,
                'active' => true,
                'sort' => 50,
            ],
            'field6' => [
                'title' => 'Город',
                'intro' => '',
                'type' => 'text',
                'default' => '',
                'options' => [
                ],
                'req' => false,
                'multi' => false,
                'active' => true,
                'sort' => 60,
            ],
            'field7' => [
                'title' => 'Счёт',
                'intro' => '',
                'type' => 'text',
                'default' => '',
                'options' => [
                ],
                'req' => false,
                'multi' => false,
                'active' => true,
                'sort' => 70,
            ],
            'field8' => [
                'title' => 'BLZ',
                'intro' => '',
                'type' => 'text',
                'default' => '',
                'options' => [
                ],
                'req' => false,
                'multi' => false,
                'active' => true,
                'sort' => 80,
            ],
            'field9' => [
                'title' => 'Банк',
                'intro' => '',
                'type' => 'text',
                'default' => '',
                'options' => [
                ],
                'req' => false,
                'multi' => false,
                'active' => true,
                'sort' => 90,
            ],
        ],
        'node' => [
            'media' => [
                'subtitle' => [
                    'title' => '_NODE_SUBTITLE',
                    'intro' => '',
                    'type' => 'text',
                    'default' => '',
                    'options' => [
                        'max' => 100,
                    ],
                    'req' => false,
                    'multi' => false,
                    'active' => true,
                    'sort' => 10,
                ],
                'year' => [
                    'title' => '_NODE_YEAR',
                    'intro' => '',
                    'type' => 'int',
                    'default' => NULL,
                    'options' => [
                        'min' => 1,
                        'max' => 9999,
                    ],
                    'req' => false,
                    'multi' => false,
                    'active' => true,
                    'sort' => 20,
                ],
                'director' => [
                    'title' => '_NODE_DIRECTOR',
                    'intro' => '',
                    'type' => 'text',
                    'default' => '',
                    'options' => [
                        'max' => 100,
                    ],
                    'req' => false,
                    'multi' => false,
                    'active' => true,
                    'sort' => 30,
                ],
                'cast' => [
                    'title' => '_NODE_CAST',
                    'intro' => '',
                    'type' => 'text',
                    'default' => '',
                    'options' => [
                        'max' => 255,
                    ],
                    'req' => false,
                    'multi' => false,
                    'active' => true,
                    'sort' => 40,
                ],
                'creator' => [
                    'title' => '_NODE_CREATOR',
                    'intro' => '',
                    'type' => 'text',
                    'default' => '',
                    'options' => [
                        'max' => 100,
                    ],
                    'req' => false,
                    'multi' => false,
                    'active' => true,
                    'sort' => 50,
                ],
                'runtime' => [
                    'title' => '_NODE_RUNTIME',
                    'intro' => '',
                    'type' => 'text',
                    'default' => '',
                    'options' => [
                        'max' => 100,
                    ],
                    'req' => false,
                    'multi' => false,
                    'active' => true,
                    'sort' => 60,
                ],
                'language' => [
                    'title' => '_LANGUAGE',
                    'intro' => '',
                    'type' => 'text',
                    'default' => '',
                    'options' => [
                        'max' => 100,
                    ],
                    'req' => false,
                    'multi' => false,
                    'active' => true,
                    'sort' => 70,
                ],
                'notes' => [
                    'title' => '_NOTE',
                    'intro' => '',
                    'type' => 'textarea',
                    'default' => '',
                    'options' => [
                        'max' => 262144,
                    ],
                    'req' => false,
                    'multi' => false,
                    'active' => true,
                    'sort' => 80,
                ],
                'format' => [
                    'title' => '_NODE_MFORMAT',
                    'intro' => '',
                    'type' => 'text',
                    'default' => '',
                    'options' => [
                        'max' => 100,
                    ],
                    'req' => false,
                    'multi' => false,
                    'active' => true,
                    'sort' => 90,
                ],
                'quality' => [
                    'title' => '_NODE_QUALITY',
                    'intro' => '',
                    'type' => 'text',
                    'default' => '',
                    'options' => [
                        'max' => 100,
                    ],
                    'req' => false,
                    'multi' => false,
                    'active' => true,
                    'sort' => 100,
                ],
                'filesize' => [
                    'title' => '_SIZE',
                    'intro' => '',
                    'type' => 'text',
                    'default' => '',
                    'options' => [
                        'max' => 100,
                    ],
                    'req' => false,
                    'multi' => false,
                    'active' => true,
                    'sort' => 110,
                ],
                'release' => [
                    'title' => '_NODE_RELEASE',
                    'intro' => '',
                    'type' => 'text',
                    'default' => '',
                    'options' => [
                        'max' => 100,
                    ],
                    'req' => false,
                    'multi' => false,
                    'active' => true,
                    'sort' => 120,
                ],
            ],
        ],
    ],
];
