<?php
# Author: Eduard Laas
# Copyright © 2005 - 2026 SLAED
# License: GNU GPL 3
# Website: slaed.net

return [
    '_meta' => [
        'base_fingerprint' => 'a5404a7dd71e4269f7fdad0d7bdcc8a508c6914f',
        'cache_version' => 1,
        'generated_at' => 1779197745,
    ],
    '_config' => [
        'auto_links' => [
            'addmail' => '1',
            'anum' => '50',
            'anump' => '10',
            'img' => 'slaed_3.gif',
            'limit' => '20',
            'num' => '10',
            'nump' => '8',
            'strip' => '15',
        ],
        'changelog' => [
            'cachettl' => '900',
            'exporten' => '1',
            'ghowner' => 'SLAED-CMS',
            'ghrepo' => 'SLAED-CMS-6.3',
            'ghtoken' => '',
            'grpdate' => '1',
            'limit' => '500',
            'perpage' => '10',
            'showfile' => '1',
            'showstat' => '1',
            'source' => 'github',
        ],
        'comments' => [
            'addmail' => '1',
            'alink' => '0',
            'anonpost' => '1',
            'anum' => '25',
            'anump' => '8',
            'edit' => '600',
            'letter' => '100',
            'link' => '0',
            'num' => '15',
            'nump' => '8',
            'privat' => '1',
            'profil' => '1',
            'send' => '30',
            'sort' => '0',
            'web' => '0',
        ],
        'contact' => [
            'admins' => '1',
            'info' => '[b]Наши координаты[/b]<br>
<br>
S-Test - Webhosting, Design<br>
Генеральный директор: Test Testow<br>
Улица: Im Test 46<br>
Индекс/Город: D-50179 Ostertest<br>
Телефон: +49 456960634',
        ],
        'content' => [
            'anum' => '25',
            'anump' => '10',
            'num' => '25',
            'nump' => '10',
        ],
        'db' => [
            'charset' => 'utf8mb4',
            'collate' => 'utf8mb4_unicode_ci',
            'engine' => 'InnoDB',
            'host' => 'MariaDB-11.7',
            'name' => 'slaed',
            'pass' => '',
            'prefix' => 'sport',
            'sync' => '0',
            'uname' => 'root',
        ],
        'faq' => [
            'add' => '1',
            'addmail' => '1',
            'addquest' => '1',
            'anum' => '50',
            'anump' => '10',
            'autor' => '1',
            'catdesc' => '1',
            'date' => '1',
            'defis' => '%C2%BB',
            'homcat' => '0',
            'letter' => '1',
            'link' => '1',
            'linknum' => '5',
            'listnum' => '50',
            'num' => '10',
            'nump' => '5',
            'rate' => '1',
            'read' => '1',
            'subcat' => '1',
            'viewcat' => '0',
        ],
        'favorites' => [
            'anum' => '50',
            'anump' => '10',
            'favact' => '1',
            'favorites' => '500',
            'num' => '50',
            'nump' => '10',
        ],
        'fields' => [
            'account' => 'Версия системы|2.3 Lite, 2.4 Lite,3.3 Pro|3|2||Ваше имя|Андрей|1|2||Ваше мыло|email@domain.net|1|1||0|0|1|1||0|0|1|1||0|0|1|1||0|0|1|1||0|0|1|1||0|0|1|1||0|0|1|1',
            'content' => 'Test|Test|1|2||Test2|Test2|2|2||0|0|1|1||0|0|1|1||0|0|1|1||0|0|1|1||0|0|1|1||0|0|1|1||0|0|1|1||0|0|1|1',
            'forum' => 'Test|Test,Test2,Test3,Test11|3|2||Test2|Tes4,Test5,Test6,Test22|3|2||0|0|3|1||0|0|3|1||0|0|1|1||0|0|1|1||0|0|1|1||0|0|1|1||0|0|1|1||0|0|1|1',
            'help' => 'Test|Test,Test2,Test3,Test11|3|2||Test2|Tes4,Test5,Test6,Test22|3|2||Test3|Test7,Test8,Test9,Test91|3|1||Test4|Test10,Test11,Test12|3|1||0|0|1|1||0|0|1|1||0|0|1|1||0|0|1|1||0|0|1|1||0|0|1|1',
            'news' => 'Test|Test|1|2||Test2|Test2|2|2||0|0|1|1||0|0|1|1||0|0|1|1||0|0|1|1||0|0|1|1||0|0|1|1||0|0|1|1||0|0|1|1',
            'order' => 'WebMoney Z|Кошелек Z|1|1||0|Ваше имя|1|2||0|Ваша фамилия|1|2||0|0|1|1||0|0|1|1||0|0|1|1||0|0|1|1||0|0|1|1||0|0|1|1||0|0|1|1',
        ],
        'files' => [
            'add' => '1',
            'addmail' => '1',
            'addquest' => '1',
            'anum' => '25',
            'anump' => '10',
            'autor' => '1',
            'broc' => '1',
            'catdesc' => '1',
            'date' => '1',
            'defis' => '%C2%BB',
            'down' => '1',
            'hits' => '1',
            'homcat' => '1',
            'letter' => '1',
            'link' => '1',
            'linknum' => '5',
            'listnum' => '25',
            'max_size' => '10485760',
            'num' => '10',
            'nump' => '5',
            'path' => 'uploads/files/public',
            'rate' => '1',
            'read' => '1',
            'stream' => '0',
            'subcat' => '1',
            'temp' => 'uploads/files/temp',
            'typefile' => 'zip,gzip,7z,rar,tar',
            'upload' => '1',
            'viewcat' => '1',
        ],
        'filetype' => [
            '7zip' => '<a href="[src]" target="_blank" title="[title]">[title]</a>',
            'bmp' => '<a rel="[rel]" title="[title]" href="[src]" class="screens"><img src="[tsrc]" style="max-width: [twidth]px; height: auto; float: [align]; margin: 0 5px 5px 0;" alt="[title]"></a>',
            'gif' => '<a rel="[rel]" title="[title]" href="[src]" class="screens"><img src="[tsrc]" style="max-width: [twidth]px; height: auto; float: [align]; margin: 0 5px 5px 0;" alt="[title]"></a>',
            'gzip' => '<a href="[src]" target="_blank" title="[title]">[title]</a>',
            'jpeg' => '<a rel="[rel]" title="[title]" href="[src]" class="screens"><img src="[tsrc]" style="max-width: [twidth]px; height: auto; float: [align]; margin: 0 5px 5px 0;" alt="[title]"></a>',
            'jpg' => '<a rel="[rel]" title="[title]" href="[src]" class="screens"><img src="[tsrc]" style="max-width: [twidth]px; height: auto; float: [align]; margin: 0 5px 5px 0;" alt="[title]"></a>',
            'm4a' => '<video width="[width]" height="[height]" controls><source src="[src]" type="video/mp4"></video>',
            'm4b' => '<video width="[width]" height="[height]" controls><source src="[src]" type="video/mp4"></video>',
            'm4p' => '<video width="[width]" height="[height]" controls><source src="[src]" type="video/mp4"></video>',
            'm4r' => '<video width="[width]" height="[height]" controls><source src="[src]" type="video/mp4"></video>',
            'm4v' => '<video width="[width]" height="[height]" controls><source src="[src]" type="video/mp4"></video>',
            'mp3' => '<audio controls><source src="[src]" type="audio/mpeg"></audio>',
            'mp4' => '<video width="[width]" height="[height]" controls><source src="[src]" type="video/mp4"></video>',
            'oga' => '<video width="[width]" height="[height]" controls><source src="[src]" type="video/ogg"></video>',
            'ogg' => '<video width="[width]" height="[height]" controls><source src="[src]" type="video/ogg"></video>',
            'ogv' => '<video width="[width]" height="[height]" controls><source src="[src]" type="video/ogg"></video>',
            'ogx' => '<video width="[width]" height="[height]" controls><source src="[src]" type="video/ogg"></video>',
            'opus' => '<video width="[width]" height="[height]" controls><source src="[src]" type="video/ogg"></video>',
            'png' => '<a rel="[rel]" title="[title]" href="[src]" class="screens"><img src="[tsrc]" style="max-width: [twidth]px; height: auto; float: [align]; margin: 0 5px 5px 0;" alt="[title]"></a>',
            'rar' => '<a href="[src]" target="_blank" title="[title]">[title]</a>',
            'spx' => '<video width="[width]" height="[height]" controls><source src="[src]" type="video/ogg"></video>',
            'swf' => ' <embed src="[src]" height="[height]" width="[width]" type="application/x-shockwave-flash">',
            'wav' => '<audio controls><source src="[src]" type="audio/wav"></audio>',
            'wave' => '<audio controls><source src="[src]" type="audio/wav"></audio>',
            'webm' => '<video width="[width]" height="[height]" controls><source src="[src]" type="video/webm"></video>',
            'zip' => '<a href="[src]" target="_blank" title="[title]">[title]</a>',
        ],
        'forum' => [
            'add' => '1',
            'addmail' => '1',
            'anonpost' => '0',
            'defis' => '%C2%BB',
            'ledit' => '1',
            'letter' => '100',
            'listnum' => '50',
            'num' => '10',
            'pnum' => '10',
            'pop' => '25',
            'privat' => '1',
            'profil' => '1',
            'qreply' => '1',
            'recycle' => '98',
            'sort' => '1',
            'web' => '1',
        ],
        'adesc' => '1',
        'admcol' => '6',
        'admin_c' => 'panel',
        'admin_logo' => 'slaed-logo-wordmark-gradient-blue.svg',
        'adminfo' => '1',
        'admininfo' => 'Информация, которая будет доступна всем авторам. Отображение данной информации производится в верхней части панели администратора системы.',
        'adminmail' => 'slaedpro@mail.ru',
        'agraph' => '1',
        'alang' => '0',
        'amod' => 'news',
        'aschema' => '1',
        'bots' => 'AdsBot-Google=AdsBot Google,Aport Catalog Robot=Aport Catalog Bot,Aport=Aport Bot,AportCatalogRobot/2.0=Aport Catalog Bot,archive_org=Archive.org Bot,Ask Jeeves=Ask Jeeves Bot,AutoLuba/1.0=Yandex-MNT Bot,Baiduspider+=Baidu Spider,Begun Robot=Begun Bot,BlogPulse=BlogPulse Bot,booch=Booch Bot,CazoodleBot/=CazoodleBot,Crawler=SEO Crawler,FeedBurner/=FeedBurner,Feedfetcher-Google=Google Feedfetcher,FeedValidator=FeedValidator,GetSmart=Get Smart Bot,GigaBlast=Gigablast Bot,Gigabot/=Gigabot Bot,Google Desktop=Google Desktop,Googlebot=Google Bot,Googlebot-Image/=Google Image Bot,grub-client=Grub Client Bot,ia_archiver=IA.Archiver Bot,igdeSpyder=Igde Bot,Jetbot=Jet Bot,libwww=Punto Bot,libwww-perl/=Rambler Feed,liveinternet spider=Liveinternet Bot,Lycos=Lycos Bot,Mail.Ru=Mail.Ru Bot,Mediapartners-Google=Google Adsense Bot,MJ12bot/=Majestic-12 Bot,MLBot=MLBot,MnoGoSearch=Mno Go Search Bot,msnbot/=MSN Bot,msnbot-media/=MSNbot Media,msnbot-NewsBlogs/=MSN NewsBlogs,msnbot-webmaster/=Live Bot,NaverBot=Naver Bot,oBot=oBot,OOZBOT/=Setooz Bot,Openbot=Openfind Bot,psbot/=Psbot,Rambler=Rambler Bot,Scooter/=Alta Vista Bot,slurp@inktomi=Hot Bot,Speedy Spider=Speedy Spider,StackRambler=Stack Rambler Bot,TurnitinBot=Turnitin Bot,TurtleScanner=Turtle Scanner Bot,Twiceler-0.9=Cuill Bot,VadixBot=VadixBot Bot,Validome XML-Validator=Validome XML-Validator,Vampire=Net Vampire Bot,W3 SiteSearch Crawler=W3 Sitesearch,W3C_CSS_Validator_JFouffa/=W3C CSS Validator,W3C_Validator/=W3C Validator,W3C-checklink/=W3C Link Checker,WebAlta Crawler/=WebAlta Bot,WebCrawler=Fast Bot,Web-sniffer/=Web-sniffer,WebZIP=WebZIP Bot,WhatUSeek=What You Seek Bot,www.cys.ru=CYS Bot,XML Sitemaps Generator=XML Sitemaps Generator,YaDirectBot/=Yandex Direct,Yahoo! Slurp=Yahoo Bot,Yahoo!=Yahoo Bot,YahooFeedSeeker/=YahooSeeker Bot,Yahoo-MMCrawler/=Yahoo MMCrawler Bot,Yandex=Yandex Bot,YandexBlog/=YandexBlog Bot,Yanga WorldSearch Bot=Yanga WorldSearch Bot,ZipppBot=Zippp Bot',
        'botsact' => '1',
        'cache' => '0',
        'cache_b' => '0',
        'cache_c' => '0',
        'cache_css' => '0',
        'cache_d' => '7',
        'cache_script' => '0',
        'cache_t' => '600',
        'capkey' => '6Lc7qf8cAAAAAOPyBdjLMe_3AaO9kPSVqQzZQ0nI',
        'capsec' => '6Lc7qf8cAAAAAJ_X0LuY2FFJziwWWDnuNd3g-nR9',
        'censor' => '1',
        'censor_l' => 'antislaed,netlevel,sunvas',
        'censor_r' => '***',
        'clickable' => '0',
        'close' => '0',
        'css_c' => '0',
        'css_e' => '0',
        'css_f' => 'plugins/highlightjs/slaed-theme.css',
        'css_h' => '0',
        'ctitle' => '1',
        'db_t' => '1',
        'dbsync' => '0',
        'defis' => '-',
        'dev_mode' => '0',
        'dletter' => '160',
        'editor' => [
            'user' => 'plain',
            'admin' => 'plain',
            'code' => 'codemirror',
        ],
        'fbots' => '21.by,a-counter.com.ua,about.com,acoon.com,aeiwi.com,all.by,alltheweb.com,altavista.com,amfibi.com,aolsearch.aol.com,aport.ru,ask.com,atlasua.net,ay.com.ua,baidu.com,belarusinfo.by,bigmir.net,bing.com,br.by,britannica.com,catalog.bel.biz,catalog.svich.com,codavr.ru,date.bs,dmoz.org,dogpile.com,entireweb.com,euroseek.net,exactseek.com,exalead.frsearch,excite.com,filesearch.ru,gala.net,gde.ru,genon.ru,gigablast.com,google.com,google.com.ua,google.de,google.net,google.ru,gugle.by,holmes.adamant.ua,hotbot.com,imhalal.com,info.com,infospace.com,ixquick.com,km.ru,links2go.com,list.np.by,liveinternet.ru,looksmart.com,lycos.com,lycos.ru,mail.ru,mamma.com,meta.ua,metabot.ru,metacrawler.com,minskin.net,myahint.com,mysearch.com,myway.com,najdivse.com,netoteka.ru,netsearch.org,nigma.ru,nol9.ru,online.ua,open.by,pepesearch.com,qango.com,qs.kiev.ua,rambler.ru,ru.yahoo.com,scrubtheweb.com,search.aol.com,search.com,search.com.ua,search.msn.com,search.yippy.com,searchking.com,sova.com.ua,teoma.com,tinEye.com,tit.by,tut.by,ualist.com,uaport.net,uaportal.com,ukrbiznes.com,ukrweb.com.ua,url.by,usluga.by,walhello.info,webalta.ru,webcrawler.com,websearch.com,webwombat.com.au,wisenut.com,ya.ru,yahoo.com,yandex.ru,zoneru.org,zubr.com',
        'flags' => '1',
        'geoip_anon' => '1',
        'geoip_asn' => 'storage/geoip/asn.mmdb',
        'geoip_cache' => '86400',
        'geoip_country' => 'storage/geoip/country.mmdb',
        'geoip_enabled' => '1',
        'geoip_store' => '0',
        'geoip_test' => '217.50.80.228',
        'gfx_chk' => '0',
        'graph' => '<meta property="og:site_name" content="[site]">
<meta property="og:locale" content="[loc]">
<meta property="og:title" content="[title]">
<meta property="og:description" content="[desc]">
<meta property="og:image" content="[img]">
<meta property="og:type" content="[type]">
<meta property="og:url" content="[url]">',
        'gtime' => 'Europe/Berlin',
        'homeurl' => 'https://slaed.loc',
        'ip_link' => 'https://whatismyipaddress.com/ip/',
        'language' => 'ru',
        'lic_f' => 'IFNMQUVELiBBbGwgcmlnaHRzIHJlc2VydmVkLg==',
        'lic_h' => 'UG93ZXJlZCBieSA8YSBocmVmPSJodHRwczovL3NsYWVkLm5ldCIgdGFyZ2V0PSJfYmxhbmsiIHRpdGxlPSJTTEFFRCBDTVMiPlNMQUVEIENNUzwvYT4gJmNvcHk7IDIwMDUt',
        'ltitle' => '1',
        'message' => '1',
        'module' => 'changelog',
        'mtemp' => 'Здравствуйте!

[text]

С наилучшими пожеланиями,

SLAED CMS - Support
https://slaed.net
support@slaed.net',
        'multilingual' => '1',
        'quality' => '4',
        'rewrite' => '0',
        'schema' => '<script type="application/ld+json">
{
	"@context": "https://schema.org",
	"@type": "Organization",
	"name": "[site]",
	"url": "[homeurl]",
	"image": "[logo]",
	"sameAs": [
		"https://vk.com/slaed_cms",
		"https://www.facebook.com/SLAED-CMS-577310846059054",
		"https://twitter.com/slaed_cms",
		"https://plus.google.com/112343714768886483056"
	]
}
</script>
<script type="application/ld+json">
{
	"@context": "https://schema.org",
	"@type": "Article",
	"name": "[title]",
	"description": "[desc]",
	"articleSection": "[ctitle]",
	"datePublished": "[time]",
	"dateModified": "[mtime]",
	"image": "[img]",
	"url": "[url]",
	"headline": "[headline]",
	"author": {
		"@type": "Person",
		"name": "[author]"
	},
	"publisher": {
		"@type": "Organization",
		"name": "[site]",
		"url": "[homeurl]",
		"logo": {
			"@type": "ImageObject",
			"name": "[site]",
			"url": "[logo]"
		}
	},
	"mainEntityOfPage": {
		"@type": "WebPage",
		"name": "[site]",
		"url": "[homeurl]"
	}
}
</script>',
        'script_a' => '0',
        'script_b' => '0',
        'script_c' => '0',
        'script_f' => 'plugins/htmx/htmx.min.js,plugins/system/global-func.js,plugins/system/slaed.js,plugins/tablesort/tablesort.min.js',
        'script_h' => '0',
        'sep' => '%2F',
        'sess_t' => '900',
        'session' => '1',
        'site_logo' => 'slaed-logo-mark-gradient-blue.svg',
        'sitekey' => 'S85csc5AwUV1wSeh957IUf1Uw',
        'sitename' => 'Название сайта',
        'slogan' => 'SLAED CMS - Современная система управления содержимым динамичных сайтов и мощная система управления интернет-порталами.',
        'startdate' => '2013-06-17 00:00:00',
        'syntax' => '2',
        'theme' => 'lite',
        'title' => '1',
        'tsep' => '-',
        'user_c' => 'slaed',
        'user_c_t' => '2592000',
        'var_view' => '1',
        'variables' => '0,1,1,1,1,1,1,0,1',
        'version' => '6.3.0 Phoenix',
        'help' => [
            'add' => '1',
            'addmail' => '1',
            'anum' => '50',
            'anump' => '10',
            'catdesc' => '1',
            'date' => '1',
            'defis' => '%C2%BB',
            'letter' => '1',
            'listnum' => '50',
            'num' => '5',
            'nump' => '5',
            'read' => '1',
            'subcat' => '1',
        ],
        'jokes' => [
            'add' => '1',
            'addmail' => '1',
            'addquest' => '1',
            'anum' => '50',
            'anump' => '10',
            'catdesc' => '1',
            'date' => '1',
            'defis' => '%C2%BB',
            'homcat' => '1',
            'num' => '10',
            'nump' => '5',
            'rate' => '1',
            'subcat' => '1',
        ],
        'lang' => [
            'count' => '5',
            'key' => '',
            'lang' => 'ru',
            'per_page' => '100',
        ],
        'links' => [
            'add' => '1',
            'addmail' => '1',
            'addquest' => '1',
            'anum' => '25',
            'anump' => '10',
            'autor' => '1',
            'broc' => '1',
            'catdesc' => '1',
            'date' => '1',
            'defis' => '%C2%BB',
            'hits' => '1',
            'homcat' => '0',
            'letter' => '1',
            'link' => '1',
            'linknum' => '5',
            'links' => '1',
            'listnum' => '25',
            'num' => '10',
            'nump' => '5',
            'rate' => '1',
            'read' => '1',
            'subcat' => '1',
            'viewcat' => '0',
        ],
        'media' => [
            'add' => '1',
            'addmail' => '1',
            'addquest' => '1',
            'anum' => '25',
            'anump' => '10',
            'autor' => '1',
            'broc' => '1',
            'catdesc' => '1',
            'date' => '1',
            'defis' => '%C2%BB',
            'format' => 'DVD,DivX,XviD,SVCD,VCD,mp3,Zip,GZip,Rar',
            'hide' => '1',
            'homcat' => '1',
            'lang' => 'Русский любительский перевод,Русский профессиональный перевод,Русский дублированный,Русский,Deutsch,English',
            'letter' => '1',
            'link' => '1',
            'linknum' => '2',
            'links' => '10',
            'listnum' => '25',
            'mdefis' => '%2F',
            'num' => '10',
            'nump' => '5',
            'quality' => 'DVD,DVDRip,VCD,VHS',
            'rate' => '1',
            'read' => '1',
            'subcat' => '1',
            'viewcat' => '1',
        ],
        'modules' => [
            'account' => [
                'lang' => '_USERS',
                'img' => 'users.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '2',
                'top' => '0',
                'type' => '1',
            ],
            'admins' => [
                'lang' => '_ADMINS',
                'img' => 'admins.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '0',
            ],
            'auto_links' => [
                'lang' => '_A_LINKS',
                'img' => 'auto_links.png',
                'active' => '0',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '1',
            ],
            'blocks' => [
                'lang' => '_BLOCKS',
                'img' => 'blocks.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '0',
            ],
            'categories' => [
                'lang' => '_CATEGORIES',
                'img' => 'categories.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '0',
            ],
            'changelog' => [
                'lang' => '_CHANGELOG',
                'img' => 'editor.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '2',
                'top' => '0',
                'type' => '1',
            ],
            'clients' => [
                'lang' => '_CLIENTS',
                'img' => 'clients.png',
                'active' => '1',
                'view' => '1',
                'menu' => '1',
                'group' => '6',
                'side' => '2',
                'top' => '0',
                'type' => '1',
            ],
            'comments' => [
                'lang' => '_COMMENTS',
                'img' => 'comments.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '0',
            ],
            'config' => [
                'lang' => '_PREFERENCES',
                'img' => 'config.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '0',
            ],
            'contact' => [
                'lang' => '_FEEDBACK',
                'img' => 'contact.png',
                'active' => '1',
                'view' => '1',
                'menu' => '1',
                'group' => '0',
                'side' => '2',
                'top' => '0',
                'type' => '1',
            ],
            'content' => [
                'lang' => '_CONTENT',
                'img' => 'content.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '2',
                'top' => '0',
                'type' => '1',
            ],
            'database' => [
                'lang' => '_DATABASE',
                'img' => 'database.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '0',
            ],
            'editor' => [
                'lang' => '_EDITOR',
                'img' => 'editor.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '0',
            ],
            'faq' => [
                'lang' => '_FAQ',
                'img' => 'faq.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '2',
                'top' => '0',
                'type' => '1',
            ],
            'favorites' => [
                'lang' => '_FAVORITES',
                'img' => 'favorites.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '0',
            ],
            'fields' => [
                'lang' => '_FIELDS',
                'img' => 'fields.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '0',
            ],
            'files' => [
                'lang' => '_FILES',
                'img' => 'files.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '2',
                'top' => '0',
                'type' => '1',
            ],
            'forum' => [
                'lang' => '_FORUM',
                'img' => 'forum.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '2',
                'top' => '0',
                'type' => '1',
            ],
            'groups' => [
                'lang' => '_GROUPS',
                'img' => 'groups.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '0',
            ],
            'help' => [
                'lang' => '_HELP',
                'img' => 'help.png',
                'active' => '1',
                'view' => '1',
                'menu' => '1',
                'group' => '2',
                'side' => '2',
                'top' => '0',
                'type' => '1',
            ],
            'jokes' => [
                'lang' => '_JOKES',
                'img' => 'jokes.png',
                'active' => '0',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '1',
            ],
            'lang' => [
                'lang' => '_LANG',
                'img' => 'lang.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '0',
            ],
            'links' => [
                'lang' => '_LINKS',
                'img' => 'links.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '2',
                'top' => '0',
                'type' => '1',
            ],
            'main' => [
                'lang' => '_MAIN',
                'img' => 'favorites.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '3',
                'top' => '3',
                'type' => '1',
            ],
            'media' => [
                'lang' => '_MEDIA',
                'img' => 'media.png',
                'active' => '0',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '1',
            ],
            'messages' => [
                'lang' => '_MESSAGES',
                'img' => 'messages.png',
                'active' => '1',
                'view' => '1',
                'menu' => '1',
                'group' => '0',
                'side' => '2',
                'top' => '0',
                'type' => '0',
            ],
            'modules' => [
                'lang' => '_MODULES',
                'img' => 'modules.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '0',
            ],
            'money' => [
                'lang' => '_MONEY',
                'img' => 'money.png',
                'active' => '0',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '2',
                'top' => '0',
                'type' => '1',
            ],
            'monitor' => [
                'lang' => '_MONITOR',
                'img' => 'monitor.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '0',
            ],
            'news' => [
                'lang' => '_NEWS',
                'img' => 'news.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '2',
                'top' => '0',
                'type' => '1',
            ],
            'newsletter' => [
                'lang' => '_NEWSLETTER',
                'img' => 'newsletter.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '0',
            ],
            'order' => [
                'lang' => '_ORDER',
                'img' => 'order.png',
                'active' => '0',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '1',
            ],
            'pages' => [
                'lang' => '_PAGES',
                'img' => 'pages.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '2',
                'top' => '0',
                'type' => '1',
            ],
            'privat' => [
                'lang' => '_PRIVAT',
                'img' => 'privat.png',
                'active' => '1',
                'view' => '1',
                'menu' => '1',
                'group' => '0',
                'side' => '2',
                'top' => '0',
                'type' => '0',
            ],
            'ratings' => [
                'lang' => '_RATINGS',
                'img' => 'ratings.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '0',
            ],
            'recommend' => [
                'lang' => '_RECOMMEND',
                'img' => 'contact.png',
                'active' => '1',
                'view' => '1',
                'menu' => '1',
                'group' => '0',
                'side' => '2',
                'top' => '0',
                'type' => '1',
            ],
            'referers' => [
                'lang' => '_REFERERS',
                'img' => 'referers.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '0',
            ],
            'replace' => [
                'lang' => '_REPLACE',
                'img' => 'replace.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '0',
            ],
            'rss' => [
                'lang' => '_RSS',
                'img' => 'rss.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '2',
                'top' => '0',
                'type' => '1',
            ],
            'scheduler' => [
                'lang' => '_SCHEDULER',
                'img' => 'scheduler.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '0',
            ],
            'search' => [
                'lang' => '_SEARCH',
                'img' => 'find.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '2',
                'top' => '0',
                'type' => '1',
            ],
            'security' => [
                'lang' => '_SECURITY',
                'img' => 'security.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '0',
            ],
            'shop' => [
                'lang' => '_SHOP',
                'img' => 'shop.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '2',
                'top' => '0',
                'type' => '1',
            ],
            'sitemap' => [
                'lang' => '_SITEMAP',
                'img' => 'sitemap.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '2',
                'top' => '0',
                'type' => '1',
            ],
            'statistic' => [
                'lang' => '_STATISTIC',
                'img' => 'statistic.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '0',
            ],
            'template' => [
                'lang' => '_TEMPLATE',
                'img' => 'template.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '0',
            ],
            'uploads' => [
                'lang' => '_UPLOADS',
                'img' => 'uploads.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '0',
                'top' => '0',
                'type' => '0',
            ],
            'users' => [
                'lang' => '_TOPUSERS',
                'img' => 'users.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '2',
                'top' => '0',
                'type' => '1',
            ],
            'voting' => [
                'lang' => '_VOTING',
                'img' => 'voting.png',
                'active' => '1',
                'view' => '0',
                'menu' => '1',
                'group' => '0',
                'side' => '2',
                'top' => '0',
                'type' => '1',
            ],
            'whois' => [
                'lang' => '_WHOIS',
                'img' => 'whois.png',
                'active' => '1',
                'view' => '1',
                'menu' => '1',
                'group' => '0',
                'side' => '2',
                'top' => '0',
                'type' => '1',
            ],
        ],
        'money' => [
            'ad' => '1',
            'an' => '1',
            'anum' => '50',
            'anump' => '10',
            'autor' => 'PLZ/Ort: 49179 Ostercappeln<br>
Adresse: Im Siek 6<br>
Telefon: +49 1799620634<br>
E-Mail: [mail=support@slaed.net]support@slaed.net[/mail]<br>
Internet: [url=http://www.slaed.net]http://www.slaed.net[/url]',
            'bal' => '300',
            'form' => 'Кошелек WebMoney,Vorname,Name,Strasse,PLZ,Ort,IBAN,BIC-/SWIFT-Code,Kreditinstitut',
            'info' => 'Спасибо за заказ! Ваша заявка получена и поставлена в очередь на обработку. После её проверки администратором при соответствии всем требованиям, указанным в условиях обмена, Вы получите письменное уведомление на указанный при заказе контактный E-Mail с детальной информацией для дальнейших действий. Как правило, эта операция занимает не более 24 часов.',
            'kurs' => '1.15',
            'kurs2' => '71',
            'mail' => 'support@slaed.net',
            'pr' => '0',
            'proz' => '10',
            'sendinfo' => '[center][b][color=red]Спасибо за заказ![/color][/b][/center]<br>
[justify]Ваша заявка одобрена администратором и поставлена в очередь на обработку. Произведите оплату по указанному ниже способу. После этого, не позже, чем через 48 часов после поступления суммы на наш счет, на указанный Вами Z кошелек WebMoney будет перечислена соответствующая сумма, о чем Вы будете уведомлены по указанному Вами при заказе контактному E-Mail адресу.[/justify]<br>
<br>
[b]Данные для перевода[/b]<br>
<br>
Verwendungszweck/Firma: SLAED WebMoney<br>
Kontoinhaber: Eduard Laas<br>
Bank: Sparkasse Osnabrueck<br>
BLZ: 26550105<br>
Konto: 14071385',
            'text' => '[usehtml]<br>
&lt;h4&gt;Банковский перевод денежных средств WebMoney в Германии&lt;/h4&gt;&lt;br&gt;<br>
&lt;a href=&quot;https://passport.webmoney.ru/asp/certView.asp?wmid=429420748216&quot; target=&quot;_blank&quot; title=&quot;Аттестованный участник WebMoney - Аттестат продавца&quot;&gt;&lt;img src=&quot;http://www.slaed.net/uploads/all/WebMoney.gif&quot; alt=&quot;Аттестованный участник WebMoney - Аттестат продавца&quot; style=&quot;float: left; margin: 5px 5px 0 0;&quot;&gt;&lt;/a&gt;&lt;div style=&quot;text-align: justify;&quot;&gt;Наш проект осуществляет обмен денежных средств банковским переводом из Германии в систему WebMoney. Произвести перевод на наш банковский счёт в Германию Вы можете из самой Германии, а так же любой другой страны Евросоюза. Обмен производится в евровалюте или в любой другой валюте по курсу к евро.<br>
&lt;br&gt;&lt;br&gt;<br>
Комиссия, взимаемая за обмен, составляет &lt;b&gt;[proz] %&lt;/b&gt; от суммы перевода. Оплата банковским переводом принимается по курсу: &lt;b&gt;1.00 Евро = [kurs] Дол., 1.00 Евро = [kurs2] Руб.&lt;/b&gt;<br>
&lt;br&gt;&lt;br&gt;<br>
&lt;b&gt;Комиссию, взимаемую системой WebMoney за перевод денежных средств мы берём на себя. Это значит, что никаких дополнительных и скрытых расходов с Вас взиматься не будет. Вы получите именно ту сумму, которая будет указана при подсчёте.&lt;/b&gt;&lt;/div&gt;&lt;br&gt;<br>
&lt;h4&gt;Условия обмена денежных средств WebMoney в Германии&lt;/h4&gt;&lt;br&gt;<br>
&lt;div style=&quot;text-align: justify;&quot;&gt;Минимальная сумма допустимая к обмену составляет &lt;b&gt;10 Евро&lt;/b&gt;. При обмене свыше &lt;b&gt;100 Евро&lt;/b&gt; Вам необходимо выслать нам фотокопию Вашего паспорта с лицевой и обратной стороны, а так же фотокопию банковской карты. Данные, указанные в паспорте и банковской карте должны соответствовать друг другу.<br>
&lt;br&gt;&lt;br&gt;<br>
После отправки заявки Вы можете переводить деньги по указанным реквизитам. В комментариях к оплате (Verwendungszweck) укажите свой кошелек Z, R или E системы WebMoney или Имя и Фамилию, указанные Вами при оформлении заказа. На указанный в заказе кошелёк будет произведён перевод денежных средств.<br>
&lt;br&gt;&lt;br&gt;<br>
При соблюдении этих условий, не позже чем через 48 часов после поступления суммы на наш счет, на указанный Вами Z, R или E кошелек WebMoney будет перечислена соответствующая сумма, о чем Вы будете уведомлены по указанному Вами контактному E-Mail адресу.&lt;/div&gt;&lt;br&gt;<br>
&lt;h4&gt;Уведомление о рисках при обмене WebMoney в Германии&lt;/h4&gt;&lt;br&gt;<br>
&lt;div style=&quot;text-align: justify;&quot;&gt;Предлагаемые товары и услуги предоставляются не по заказу лица либо предприятия, эксплуатирующего систему WebMoney Transfer. Мы являемся независимым предприятием, оказывающим услуги, и самостоятельно принимаем решения о ценах и предложениях. Предприятия, эксплуатирующие систему WebMoney Transfer, не получают комиссионных вознаграждений или иных вознаграждений за участие в предоставлении услуг и не несут никакой ответственности за нашу деятельность.<br>
&lt;br&gt;&lt;br&gt;<br>
Аттестация, произведенная со стороны WebMoney Transfer, лишь подтверждает наши реквизиты для связи и удостоверяет личность. Она осуществляется по нашему желанию и не означает, что мы каким-либо образом связаны с продажами операторов системы WebMoney.&lt;/div&gt;<br>
[/usehtml]',
        ],
        'news' => [
            'add' => '1',
            'addmail' => '1',
            'addquest' => '1',
            'anum' => '50',
            'anump' => '5',
            'asocnum' => '5',
            'assoc' => '1',
            'autor' => '1',
            'bascol' => '1',
            'catdesc' => '1',
            'date' => '1',
            'defis' => '%C2%BB',
            'homcat' => '0',
            'letter' => '1',
            'listnum' => '25',
            'num' => '10',
            'nump' => '5',
            'rate' => '1',
            'read' => '1',
            'subcat' => '1',
            'viewcat' => '0',
        ],
        'newsletter' => [
            'active' => '0',
            'count' => '4',
        ],
        'order' => [
            'ad' => '1',
            'an' => '1',
            'anum' => '50',
            'anump' => '10',
            'info' => 'Спасибо за заказ! Ваша заявка получена и поставлена в очередь на обработку. После её проверки администратором при соответствии всем требованиям, указанным в условиях обмена, Вы получите письменное уведомление на указанный при заказе контактный E-Mail с детальной информацией для дальнейших действий. Как правило, эта операция занимает не более 24 часов.',
            'mail' => 'your_name@mail.com',
            'pr' => '0',
            'sendinfo' => '[center][b][color=orangered]Спасибо за заказ![/color][/b][/center]<br>
[justify]Ваша заявка одобрена администратором и поставлена в очередь на обработку. Произведите оплату по указанному ниже способу. После этого, не позже, чем через 48 часов после поступления суммы на наш счет, на указанный Вами Z кошелек WebMoney будет перечислена соответствующая сумма, о чем Вы будете уведомлены по указанному Вами при заказе контактному E-Mail адресу.[/justify]',
            'text' => '[center][b][color=orangered]Услуги по обмену денежных средств[/color][/b][/center]<br>
[justify]Наш проект осуществляет обмен денежных средств банковским переводом в систему WebMoney. Произвести перевод на наш банковский счёт в Германию Вы можете из самой Германии, а так же любой другой страны Евросоюза. Обмен производится в евровалюте или в любой другой валюте по курсу к евро. Комиссия, взимаемая за обмен, составляет [b]3 %[/b] от суммы перевода. Оплата банковским переводом принимается по курсу [b]1.00 € = 1.35 &#036;[/b]. Комиссию, взимаемую системой WebMoney за перевод денежных средств мы берём на себя.[/justify]<br>
[center][b][color=orangered]Условия обмена денежных средств[/color][/b][/center]<br>
[justify]Минимальная сумма допустимая к обмену составляет [b]10 €[/b]. При обмене свыше [b]250 €[/b] Вам необходимо выслать нам фотокопию Вашего паспорта с лицевой и обратной стороны, а так же фотокопию банковской карты. Данные, указанные в паспорте и банковской карте должны соответствовать друг другу.[/justify]<br>
[justify]После отправки заявки Вы можете переводить деньги по указанным реквизитам. В комментариях к оплате (Verwendungszweck) укажите свой кошелек Z системы WebMoney, указанный Вами при оформлении заказа. На данный кошелёк будет произведён перевод денежных средств.[/justify]<br>
[justify]При соблюдении этих условий не позже, чем через 48 часов после поступления суммы на наш счет, на указанный Вами Z кошелек WebMoney будет перечислена соответствующая сумма, о чем Вы будете уведомлены по указанному Вами контактному E-Mail адресу.[/justify]',
        ],
        'pages' => [
            'add' => '1',
            'addmail' => '1',
            'addquest' => '1',
            'anum' => '25',
            'anump' => '10',
            'autor' => '1',
            'catdesc' => '1',
            'date' => '1',
            'defis' => '%C2%BB',
            'homcat' => '0',
            'letter' => '1',
            'link' => '1',
            'linknum' => '5',
            'listnum' => '25',
            'num' => '10',
            'nump' => '5',
            'rate' => '1',
            'read' => '1',
            'subcat' => '1',
            'viewcat' => '1',
        ],
        'privat' => [
            'act' => '1',
            'anum' => '50',
            'anump' => '10',
            'himself' => '0',
            'letter' => '100',
            'messin' => '250',
            'messsav' => '250',
            'newmail' => '1',
            'num' => '25',
            'nump' => '10',
            'profil' => '1',
            'send' => '60',
            'web' => '1',
        ],
        'ratings' => [
            'account' => '2592000|1|0',
            'faq' => '2592000|1|0',
            'files' => '2592000|1|0',
            'forum' => '2592000|1|0',
            'help' => '2592000|1|1',
            'jokes' => '2592000|1|0',
            'links' => '2592000|1|0',
            'media' => '2592000|1|0',
            'news' => '2592000|1|0',
            'pages' => '2592000|1|0',
            'shop' => '2592000|1|0',
        ],
        'referers' => [
            'anum' => '50',
            'anump' => '10',
            'refer' => '1',
            'refer_t' => '2592000',
            'referb' => '1',
        ],
        'replace' => [
            'content' => 'Open SLAED|<a href="//slaed.net/index.php?name=files&op=view&id=1103" title="Open SLAED">Open SLAED</a>||SLAED CMS|<a href="//slaed.net/index.php?name=files&op=view&id=1529" title="SLAED CMS">SLAED CMS</a>||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0',
            'news' => 'Open SLAED|<a href="//slaed.net/index.php?name=files&op=view&id=1103" title="Open SLAED">Open SLAED</a>||SLAED CMS|<a href="//slaed.net/index.php?name=files&op=view&id=1529" title="SLAED CMS">SLAED CMS</a>||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0||0|0',
        ],
        'rss' => [
            'act' => '1',
            'max' => '50',
            'min' => '10',
            'rss' => '0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0||0|0|0',
            'temp' => '&lt;table class=&quot;sl_table_form&quot;&gt;<br>
&lt;tr&gt;&lt;td&gt;&lt;span title=&quot;[date]&quot; class=&quot;sl_date&quot;&gt;[date]&lt;/span&gt; - &lt;a href=&quot;[guid]&quot; target=&quot;_blank&quot; title=&quot;[title]&quot;&gt;[title]&lt;/a&gt;&lt;/td&gt;&lt;/tr&gt;<br>
&lt;tr&gt;&lt;td style=&quot;text-align: justify;&quot;&gt;[description]&lt;/td&gt;&lt;/tr&gt;<br>
&lt;/table&gt;',
            'use' => '1',
        ],
        'scheduler' => [
            'active' => '1',
            'cron_timeout' => '600',
            'jobs' => [
                'dbbackup' => [
                    'title' => 'Database backup',
                    'type' => 'system',
                    'active' => '1',
                    'system' => 'backup',
                    'schedule' => '30 3 * * *',
                    'priority' => '4',
                    'lock_timeout' => '1800',
                    'manual' => '1',
                    'settings' => [
                    ],
                ],
                'filescan' => [
                    'title' => 'File scan',
                    'type' => 'system',
                    'active' => '1',
                    'system' => 'filescan',
                    'schedule' => '0 3 * * *',
                    'priority' => '2',
                    'lock_timeout' => '1800',
                    'manual' => '1',
                    'settings' => [
                    ],
                ],
                'newsletter' => [
                    'title' => 'Newsletter',
                    'type' => 'system',
                    'active' => '0',
                    'system' => 'newsletter',
                    'schedule' => '1 * * * *',
                    'priority' => '1',
                    'lock_timeout' => '900',
                    'manual' => '1',
                    'settings' => [
                    ],
                ],
                'sitemap' => [
                    'title' => 'Sitemap',
                    'type' => 'system',
                    'active' => '0',
                    'system' => 'sitemap',
                    'schedule' => '15 3 * * *',
                    'priority' => '3',
                    'lock_timeout' => '1800',
                    'manual' => '1',
                    'settings' => [
                    ],
                ],
            ],
            'lock_timeout' => '1800',
            'pseudo' => '1',
            'token' => '',
            'trigger_cooldown' => '60',
        ],
        'search' => [
            'anum' => '50',
            'anump' => '10',
            'asearch' => '0',
            'mods' => 'faq,files,forum,links,news,pages,shop',
            'slet' => '3',
            'slimit' => '500',
            'snum' => '25',
            'snump' => '5',
        ],
        'security' => [
            'admin_ip' => '',
            'afile' => 'admin',
            'block' => '1',
            'blocker_cookie' => 'banned',
            'blocker_ip' => '192.0.2.0/24|dummy-c|1778015715|test ip ban C||198.51.100.1/32|fan-ip-01|1778015994|fan ip ban 01||198.51.100.2/32|fan-ip-02|1778015994|fan ip ban 02||198.51.100.3/32|fan-ip-03|1778015994|fan ip ban 03||198.51.100.4/32|fan-ip-04|1778015994|fan ip ban 04||198.51.100.5/32|fan-ip-05|1778015994|fan ip ban 05||198.51.100.6/32|fan-ip-06|1778015994|fan ip ban 06||198.51.100.7/32|fan-ip-07|1778015994|fan ip ban 07||198.51.100.8/32|fan-ip-08|1778015995|fan ip ban 08||198.51.100.9/32|fan-ip-09|1778015995|fan ip ban 09||198.51.100.10/32|fan-ip-10|1778015995|fan ip ban 10||198.51.100.11/32|fan-ip-11|1778015995|fan ip ban 11||198.51.100.12/32|fan-ip-12|1778015995|fan ip ban 12||198.51.100.13/32|fan-ip-13|1778015995|fan ip ban 13||198.51.100.14/32|fan-ip-14|1778015995|fan ip ban 14||198.51.100.15/32|fan-ip-15|1778015995|fan ip ban 15||198.51.100.16/32|fan-ip-16|1778015995|fan ip ban 16||198.51.100.17/32|fan-ip-17|1778015995|fan ip ban 17||198.51.100.18/32|fan-ip-18|1778015995|fan ip ban 18||198.51.100.19/32|fan-ip-19|1778015995|fan ip ban 19||198.51.100.20/32|fan-ip-20|1778015995|fan ip ban 20||198.51.100.21/32|fan-ip-21|1778015995|fan ip ban 21||198.51.100.22/32|fan-ip-22|1778015995|fan ip ban 22||198.51.100.23/32|fan-ip-23|1778015995|fan ip ban 23||198.51.100.24/32|fan-ip-24|1778015995|fan ip ban 24||198.51.100.25/32|fan-ip-25|1778015995|fan ip ban 25||',
            'blocker_user' => 'fanuser01|1778015995|fan user ban 01||fanuser02|1778015995|fan user ban 02||fanuser03|1778015995|fan user ban 03||fanuser04|1778015995|fan user ban 04||fanuser05|1778015995|fan user ban 05||fanuser06|1778015995|fan user ban 06||fanuser07|1778015995|fan user ban 07||fanuser08|1778015995|fan user ban 08||fanuser09|1778015995|fan user ban 09||fanuser10|1778015995|fan user ban 10||fanuser11|1778015995|fan user ban 11||fanuser12|1778015995|fan user ban 12||fanuser13|1778015995|fan user ban 13||fanuser14|1778015996|fan user ban 14||fanuser15|1778015996|fan user ban 15||fanuser16|1778015996|fan user ban 16||fanuser17|1778015996|fan user ban 17||fanuser18|1778015996|fan user ban 18||fanuser19|1778015996|fan user ban 19||fanuser20|1778015996|fan user ban 20||fanuser21|1778015996|fan user ban 21||fanuser22|1778015996|fan user ban 22||fanuser23|1778015996|fan user ban 23||fanuser24|1778015996|fan user ban 24||fanuser25|1778015996|fan user ban 25||test|1775510434|sfsdfsdfsd||test|1776288072|wqerqweqweqw||',
            'dump_skip' => '.git/
vendor/
tests/',
            'error' => '2',
            'error_log' => '1',
            'flood' => '0',
            'flood_t' => '1',
            'log' => '0',
            'log_a' => '1',
            'log_b' => '0',
            'log_d' => '0',
            'log_size' => '10485760',
            'log_u' => '0',
            'login' => '',
            'mail' => '1',
            'mail_d' => '1',
            'mail_w' => '0',
            'password' => '',
            'ref_post' => '1',
            'sess_b' => '86400',
            'sess_d' => '86400',
            'url_get' => '1',
            'url_post' => '0',
            'write_h' => '1',
            'write_w' => '0',
        ],
        'shop' => [
            'anum' => '50',
            'anump' => '10',
            'assoc' => '1',
            'assocnum' => '3',
            'bascol' => '1',
            'catdesc' => '1',
            'clients' => '0',
            'clients1' => '3',
            'clients2' => '5',
            'date' => '1',
            'defis' => '%26gt%3B',
            'homcat' => '1',
            'letter' => '1',
            'listnum' => '5',
            'mail' => 'info@slaed.net',
            'mailsend' => '1',
            'mailuser' => '1',
            'num' => '5',
            'nump' => '5',
            'part' => '1',
            'part_t' => '86400',
            'partinfo' => 'Информация для будущих партнеров',
            'partinfo2' => 'Информация для партнеров&lt;br&gt;<br>
&lt;br&gt;<br>
[url=http://localhost/index.php?name=shop&amp;amp;op=part&amp;amp;id=[id]]http://localhost/index.php?name=shop&amp;amp;op=part&amp;amp;id=[id][/url]',
            'partlink' => 'https://slaed.loc/index.php?name=shop&amp;op=part&amp;id=[id]',
            'proz' => '3',
            'proz1' => '5',
            'proz2' => '10',
            'rate' => '1',
            'read' => '1',
            'sende' => '[center][color=red][b]Cпасибо за заказ![/b][/color][/center]&lt;br&gt;<br>
&lt;br&gt;<br>
Ваша заявка отправлена и поставлена в очередь на обработку. Произведите оплату по одному из указанных ниже способов. В комментариях к оплате укажите свои имя и фамилию, указанные Вами при оформлении заказа.&lt;br&gt;<br>
&lt;br&gt;<br>
Вы должны быть зарегистрированы на проекте. Если Вы ещё не зарегистрированы, сделайте это и сообщите нам Ваш логин и персональные данные, на которые производился заказ. При соблюдении этих условий не позже, чем через 48 часов после поступления суммы на наш счет, Вам будет выдан доступ на загрузку архива, получения лицензии и технической поддержки. На указанный Вами E-Mail адрес будет выслано уведомление о предоставлении доступа клиента системы.&lt;br&gt;<br>
&lt;br&gt;<br>
[center][color=red][b]Способы оплаты услуг[/b][/color][/center]&lt;br&gt;<br>
&lt;br&gt;<br>
[b]Через платежную систему WebMoney[/b]&lt;br&gt;<br>
&lt;br&gt;<br>
[url=http://www.webmoney.ru]WebMoney[/url] - Z590919569461&lt;br&gt;<br>
[color=red]Оплата в системе WebMoney принимается по курсу: 1.00 € = 1.35 &amp;#036;[/color]',
            'shop_t' => '86400',
            'shopinfo' => 'Генеральный директор: Test Testow&lt;br&gt;<br>
Адрес: D-69079 Test, Im Test 56&lt;br&gt;<br>
Телефон: +49135204064',
            'subcat' => '1',
            'userinfo' => 'Информация для клиентов',
            'valute' => '€',
            'viewcat' => '1',
        ],
        'sitemap' => [
            'auto' => '0',
            'auto_t' => '86400',
            'dat_c' => '1',
            'dat_h' => '1',
            'dat_m' => '1',
            'dat_p' => '1',
            'fr_c' => 'weekly',
            'fr_h' => 'always',
            'fr_m' => 'daily',
            'fr_p' => 'monthly',
            'gen_c' => '1',
            'gen_h' => '1',
            'gen_m' => '1',
            'gen_p' => '1',
            'mod' => '0',
            'pr_c' => '0',
            'pr_h' => '0',
            'pr_m' => '0',
            'pr_p' => '0',
            'txt' => '1',
            'xsl' => '1',
        ],
        'statistic' => [
            'bet' => '42',
            'shi' => '22',
            'stat' => '1',
        ],
        'uploads' => [
            'account' => 'gif,jpg,jpeg,png,zip,rar|104857600|1048576|500|500|10|150|10|250|100|1|0',
            'album' => 'gif,jpg,jpeg,png,zip,rar|104857600|1048576|500|500|10|150|10|250|100|1|0',
            'all' => 'gif,jpg,jpeg,png,zip,rar|104857600|1048576|500|500|10|150|10|250|100|1|0',
            'auto_links' => 'gif,jpg,jpeg,png,zip,rar|104857600|1048576|500|500|10|150|10|250|100|1|0',
            'content' => 'gif,jpg,jpeg,png,zip,rar|104857600|1048576|500|500|10|150|10|250|100|1|0',
            'dir' => 'news',
            'faq' => 'gif,jpg,jpeg,png,zip,rar|104857600|1048576|500|500|10|150|10|250|100|1|0',
            'files' => 'gif,jpg,jpeg,png,zip,rar|104857600|1048576|500|500|10|150|10|250|100|1|0',
            'forum' => 'gif,jpg,jpeg,png,zip,rar|104857600|1048576|500|500|10|150|10|250|100|1|0',
            'height' => '500',
            'help' => 'gif,jpg,jpeg,png,zip,rar|104857600|1048576|500|500|10|150|10|250|100|1|0',
            'info' => 'gif,jpg,jpeg,png,zip,rar|104857600|1048576|500|500|10|150|10|250|100|1|0',
            'links' => 'gif,jpg,jpeg,png,zip,rar|104857600|1048576|500|500|10|150|10|250|100|1|0',
            'media' => 'gif,jpg,jpeg,png,zip,rar|104857600|1048576|500|500|10|150|10|250|100|1|0',
            'news' => 'gif,jpg,jpeg,png,zip,rar|104857600|1048576|500|500|10|150|10|250|100|1|0',
            'pages' => 'gif,jpg,jpeg,png,zip,rar|104857600|1048576|500|500|10|150|10|250|100|1|0',
            'shop' => 'gif,jpg,jpeg,png,zip,rar|104857600|1048576|500|500|10|150|10|250|100|1|0',
            'typ' => 'gif,jpg,jpeg,png,bmp,mp3,wav,wave,mp4,m4a,m4p,m4b,m4r,m4v,ogg,oga,ogv,ogx,spx,opus,webm,zip,rar,gzip,7zip,swf',
            'voting' => 'gif,jpg,jpeg,png,zip,rar|104857600|1048576|500|500|10|150|10|250|100|1|0',
            'width' => '500',
        ],
        'users' => [
            'adirectory' => 'uploads/avatars',
            'aheight' => '100',
            'amaxsize' => '51200',
            'anum' => '50',
            'anump' => '10',
            'atypefile' => 'jpg,jpeg,gif,png',
            'aupload' => '1',
            'awidth' => '100',
            'check' => '0',
            'enter' => '1',
            'mail_b' => '',
            'minpass' => '5',
            'name_b' => 'alter,drop,insert,outfile,select,truncate,union',
            'network' => '0',
            'network_c' => '<script src="//ulogin.ru/js/ulogin.js"></script>
<div id="uLogin" data-ulogin="display=panel;theme=flat;fields=nickname,first_name,last_name,email,photo;providers=vkontakte,odnoklassniki,mailru,facebook;hidden=other;redirect_uri=[url];mobilebuttons=0;"></div>',
            'news' => '1',
            'nomail' => '1',
            'point' => '1',
            'points' => '1,3,5,3,3,10,5,3,10,5,3,3,10,3,10,5,3,3,10,5,3,10,5,3,10,5,3,1,5,3,10,5,3,10,10,5,3,10,10,5,3,10,5,3,3',
            'prof' => '0',
            'reg' => '1',
            'rule' => '0',
            'rules' => 'Правила проекта',
            'theme' => '1',
            'user_t' => '2592000',
        ],
        'voting' => [
            'answ' => '25',
            'anum' => '50',
            'anump' => '10',
            'block' => '2',
            'num' => '15',
            'nump' => '5',
            'voting_t' => '2592000',
        ],
        'whois' => [
            'add' => '1',
            'addmail' => '1',
            'addquest' => '1',
            'anum' => '50',
            'anump' => '10',
        ],
    ],
];
