<?php
# Author: Eduard Laas
# 2005 - 2026 SLAED
# License: MIT
# Website: slaed.net

return [
    'modules' => [
        'account' => [
            'lang' => '_USERS',
            'icon' => 'people',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'admins' => [
            'lang' => '_ADMINS',
            'icon' => 'person-gear',
            'active' => '1',
            'view' => '2',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'auto_links' => [
            'lang' => '_A_LINKS',
            'icon' => 'arrow-left-right',
            'active' => '0',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '1',
        ],
        'blocks' => [
            'lang' => '_BLOCKS',
            'icon' => 'grid-3x3-gap',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'categories' => [
            'lang' => '_CATEGORIES',
            'icon' => 'folder',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'changelog' => [
            'lang' => '_CHANGELOG',
            'icon' => 'journal-text',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'clients' => [
            'lang' => '_CLIENTS',
            'icon' => 'briefcase',
            'active' => '1',
            'view' => '1',
            'menu' => '1',
            'group' => '6',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'comments' => [
            'lang' => '_COMMENTS',
            'icon' => 'chat-dots',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'config' => [
            'lang' => '_PREFERENCES',
            'icon' => 'gear',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'contact' => [
            'lang' => '_FEEDBACK',
            'icon' => 'envelope-open',
            'active' => '1',
            'view' => '1',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'content' => [
            'lang' => '_CONTENT',
            'icon' => 'file-earmark-text',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'database' => [
            'lang' => '_DATABASE',
            'icon' => 'database',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'editor' => [
            'lang' => '_EDITOR',
            'icon' => 'pencil-square',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'faq' => [
            'lang' => '_FAQ',
            'icon' => 'question-circle',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'favorites' => [
            'lang' => '_FAVORITES',
            'icon' => 'star',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'fields' => [
            'lang' => '_FIELDS',
            'icon' => 'input-cursor-text',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'files' => [
            'lang' => '_FILES',
            'icon' => 'folder2-open',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'forum' => [
            'lang' => '_FORUM',
            'icon' => 'chat-square-text',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'groups' => [
            'lang' => '_GROUPS',
            'icon' => 'people-fill',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'help' => [
            'lang' => '_HELP',
            'icon' => 'info-circle',
            'active' => '1',
            'view' => '1',
            'menu' => '1',
            'group' => '2',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'jokes' => [
            'lang' => '_JOKES',
            'icon' => 'emoji-laughing',
            'active' => '0',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '1',
        ],
        'lang' => [
            'lang' => '_LANG',
            'icon' => 'translate',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'links' => [
            'lang' => '_LINKS',
            'icon' => 'link-45deg',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'main' => [
            'lang' => '_MAIN',
            'icon' => 'house-door',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '3',
            'top' => '3',
            'type' => '1',
        ],
        'media' => [
            'lang' => '_MEDIA',
            'icon' => 'image',
            'active' => '0',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '1',
        ],
        'messages' => [
            'lang' => '_MESSAGES',
            'icon' => 'envelope',
            'active' => '1',
            'view' => '1',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '0',
        ],
        'modules' => [
            'lang' => '_MODULES',
            'icon' => 'gpu-card',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'money' => [
            'lang' => '_MONEY',
            'icon' => 'currency-exchange',
            'active' => '0',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'monitor' => [
            'lang' => '_MONITOR',
            'icon' => 'display',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'news' => [
            'lang' => '_NEWS',
            'icon' => 'newspaper',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'newsletter' => [
            'lang' => '_NEWSLETTER',
            'icon' => 'send',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'order' => [
            'lang' => '_ORDER',
            'icon' => 'receipt',
            'active' => '0',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '1',
        ],
        'pages' => [
            'lang' => '_PAGES',
            'icon' => 'card-text',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'privat' => [
            'lang' => '_PRIVAT',
            'icon' => 'incognito',
            'active' => '1',
            'view' => '1',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '0',
        ],
        'ratings' => [
            'lang' => '_RATINGS',
            'icon' => 'star-half',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'recommend' => [
            'lang' => '_RECOMMEND',
            'icon' => 'share',
            'active' => '1',
            'view' => '1',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'referers' => [
            'lang' => '_REFERERS',
            'icon' => 'box-arrow-in-right',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'replace' => [
            'lang' => '_REPLACE',
            'icon' => 'arrow-left-right',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'rss' => [
            'lang' => '_RSS',
            'icon' => 'rss',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'scheduler' => [
            'lang' => '_SCHEDULER',
            'icon' => 'clock-history',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'search' => [
            'lang' => '_SEARCH',
            'icon' => 'search',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'security' => [
            'lang' => '_SECURITY',
            'icon' => 'shield-lock',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'shop' => [
            'lang' => '_SHOP',
            'icon' => 'cart3',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'sitemap' => [
            'lang' => '_SITEMAP',
            'icon' => 'diagram-3',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'statistic' => [
            'lang' => '_STATISTIC',
            'icon' => 'graph-up',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'template' => [
            'lang' => '_TEMPLATE',
            'icon' => 'palette',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'uploads' => [
            'lang' => '_UPLOADS',
            'icon' => 'cloud-arrow-up',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'users' => [
            'lang' => '_TOPUSERS',
            'icon' => 'people',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'voting' => [
            'lang' => '_VOTING',
            'icon' => 'bar-chart',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'whois' => [
            'lang' => '_WHOIS',
            'icon' => 'geo-alt',
            'active' => '1',
            'view' => '1',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
    ],
];
