<?php
# Author: Eduard Laas
# Copyright (c) 2005 - 2026 SLAED
# License: GNU GPL 3
# Website: slaed.net

return [
    'modules' => [
        'account' => [
            'lang' => '_USERS',
            'img' => 'users.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'admins' => [
            'lang' => '_ADMINS',
            'img' => 'admins.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'auto_links' => [
            'lang' => '_A_LINKS',
            'img' => 'auto_links.png',
            'active' => '0',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '1',
        ],
        'blocks' => [
            'lang' => '_BLOCKS',
            'img' => 'blocks.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'categories' => [
            'lang' => '_CATEGORIES',
            'img' => 'categories.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'changelog' => [
            'lang' => '_CHANGELOG',
            'img' => 'editor.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'clients' => [
            'lang' => '_CLIENTS',
            'img' => 'clients.png',
            'active' => '1',
            'view' => '1',
            'menu' => '1',
            'group' => '6',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'comments' => [
            'lang' => '_COMMENTS',
            'img' => 'comments.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'config' => [
            'lang' => '_PREFERENCES',
            'img' => 'config.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'contact' => [
            'lang' => '_FEEDBACK',
            'img' => 'contact.png',
            'active' => '1',
            'view' => '1',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'content' => [
            'lang' => '_CONTENT',
            'img' => 'content.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'database' => [
            'lang' => '_DATABASE',
            'img' => 'database.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'editor' => [
            'lang' => '_EDITOR',
            'img' => 'editor.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'faq' => [
            'lang' => '_FAQ',
            'img' => 'faq.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'favorites' => [
            'lang' => '_FAVORITES',
            'img' => 'favorites.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'fields' => [
            'lang' => '_FIELDS',
            'img' => 'fields.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'files' => [
            'lang' => '_FILES',
            'img' => 'files.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'forum' => [
            'lang' => '_FORUM',
            'img' => 'forum.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'groups' => [
            'lang' => '_GROUPS',
            'img' => 'groups.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'help' => [
            'lang' => '_HELP',
            'img' => 'help.png',
            'active' => '1',
            'view' => '1',
            'menu' => '1',
            'group' => '2',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'jokes' => [
            'lang' => '_JOKES',
            'img' => 'jokes.png',
            'active' => '0',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '1',
        ],
        'lang' => [
            'lang' => '_LANG',
            'img' => 'lang.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'links' => [
            'lang' => '_LINKS',
            'img' => 'links.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'main' => [
            'lang' => '_MAIN',
            'img' => 'favorites.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '3',
            'top' => '3',
            'type' => '1',
        ],
        'media' => [
            'lang' => '_MEDIA',
            'img' => 'media.png',
            'active' => '0',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '1',
        ],
        'messages' => [
            'lang' => '_MESSAGES',
            'img' => 'messages.png',
            'active' => '1',
            'view' => '1',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '0',
        ],
        'modules' => [
            'lang' => '_MODULES',
            'img' => 'modules.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'money' => [
            'lang' => '_MONEY',
            'img' => 'money.png',
            'active' => '0',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'monitor' => [
            'lang' => '_MONITOR',
            'img' => 'monitor.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'news' => [
            'lang' => '_NEWS',
            'img' => 'news.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'newsletter' => [
            'lang' => '_NEWSLETTER',
            'img' => 'newsletter.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'order' => [
            'lang' => '_ORDER',
            'img' => 'order.png',
            'active' => '0',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '1',
        ],
        'pages' => [
            'lang' => '_PAGES',
            'img' => 'pages.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'privat' => [
            'lang' => '_PRIVAT',
            'img' => 'privat.png',
            'active' => '1',
            'view' => '1',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '0',
        ],
        'ratings' => [
            'lang' => '_RATINGS',
            'img' => 'ratings.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'recommend' => [
            'lang' => '_RECOMMEND',
            'img' => 'contact.png',
            'active' => '1',
            'view' => '1',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'referers' => [
            'lang' => '_REFERERS',
            'img' => 'referers.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'replace' => [
            'lang' => '_REPLACE',
            'img' => 'replace.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'rss' => [
            'lang' => '_RSS',
            'img' => 'rss.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'scheduler' => [
            'lang' => '_SCHEDULER',
            'img' => 'remote.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'search' => [
            'lang' => '_SEARCH',
            'img' => 'find.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'security' => [
            'lang' => '_SECURITY',
            'img' => 'security.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'shop' => [
            'lang' => '_SHOP',
            'img' => 'shop.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'sitemap' => [
            'lang' => '_SITEMAP',
            'img' => 'sitemap.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'statistic' => [
            'lang' => '_STATISTIC',
            'img' => 'statistic.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'template' => [
            'lang' => '_TEMPLATE',
            'img' => 'template.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'uploads' => [
            'lang' => '_UPLOADS',
            'img' => 'uploads.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '0',
            'top' => '0',
            'type' => '0',
        ],
        'users' => [
            'lang' => '_TOPUSERS',
            'img' => 'users.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'voting' => [
            'lang' => '_VOTING',
            'img' => 'voting.png',
            'active' => '1',
            'view' => '0',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
        'whois' => [
            'lang' => '_WHOIS',
            'img' => 'whois.png',
            'active' => '1',
            'view' => '1',
            'menu' => '1',
            'group' => '0',
            'side' => '2',
            'top' => '0',
            'type' => '1',
        ],
    ],
];
