<?php
# Author: Eduard Laas
# Copyright © 2005 - 2026 SLAED
# License: GNU GPL 3
# Website: slaed.net

if (!defined('FUNC_FILE')) die('Illegal file access');

$confmd = array (
  'account' => 
  array (
    'lang' => '_ACCOUNT',
    'img' => 'account.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '1',
    'top' => '0',
  ),
  'admins' => 
  array (
    'lang' => '_EDITADMINS',
    'img' => 'admins.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
    'type' => '0',
  ),
  'auto_links' => 
  array (
    'lang' => '_LINKS',
    'img' => 'auto_links.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
  ),
  'blocks' => 
  array (
    'lang' => '_BLOCKS',
    'img' => 'blocks.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
    'type' => '0',
  ),
  'categories' => 
  array (
    'lang' => '_CATEGORIES',
    'img' => 'categories.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
    'type' => '0',
  ),
  'changelog' => 
  array (
    'lang' => '_CHANGELOG',
    'img' => 'editor.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
  ),
  'clients' => 
  array (
    'lang' => '_CLIENTS',
    'img' => 'clients.png',
    'active' => '1',
    'view' => '1',
    'menu' => '1',
    'group' => '6',
    'side' => '0',
    'top' => '0',
  ),
  'comments' => 
  array (
    'lang' => '_COMMENTS',
    'img' => 'comments.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
    'type' => '0',
  ),
  'config' => 
  array (
    'lang' => '_PREFERENCES',
    'img' => 'config.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
    'type' => '0',
  ),
  'contact' => 
  array (
    'lang' => '_CONTACT',
    'img' => 'contact.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
  ),
  'content' => 
  array (
    'lang' => '_CONTENT',
    'img' => 'content.png',
    'active' => '1',
    'view' => '0',
    'menu' => '0',
    'group' => '0',
    'side' => '0',
    'top' => '0',
  ),
  'database' => 
  array (
    'lang' => '_DATABASE',
    'img' => 'database.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
    'type' => '0',
  ),
  'editor' => 
  array (
    'lang' => '_EDITOR_IN',
    'img' => 'editor.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
    'type' => '0',
  ),
  'faq' => 
  array (
    'lang' => '_FAQ',
    'img' => 'faq.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
  ),
  'favorites' => 
  array (
    'lang' => '_FAVORITES',
    'img' => 'favorites.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
    'type' => '0',
  ),
  'fields' => 
  array (
    'lang' => '_FIELDS',
    'img' => 'fields.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
    'type' => '0',
  ),
  'files' => 
  array (
    'lang' => '_FILES',
    'img' => 'files.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
  ),
  'forum' => 
  array (
    'lang' => '_FORUM',
    'img' => 'forum.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '2',
    'top' => '0',
  ),
  'groups' => 
  array (
    'lang' => '_UGROUPS',
    'img' => 'groups.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
    'type' => '0',
  ),
  'help' => 
  array (
    'lang' => '_HELP',
    'img' => 'help.png',
    'active' => '1',
    'view' => '1',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
  ),
  'jokes' => 
  array (
    'lang' => '_JOKES',
    'img' => 'jokes.png',
    'active' => '0',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
  ),
  'lang' => 
  array (
    'lang' => '_LANG',
    'img' => 'lang.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
    'type' => '0',
  ),
  'links' => 
  array (
    'lang' => '_LINKS',
    'img' => 'links.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
  ),
  'main' => 
  array (
    'lang' => '_MAIN',
    'img' => 'main.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '3',
    'top' => '3',
  ),
  'media' => 
  array (
    'lang' => '_MEDIA',
    'img' => 'media.png',
    'active' => '0',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
  ),
  'messages' => 
  array (
    'lang' => '_MESSAGES',
    'img' => 'messages.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
    'type' => '0',
  ),
  'modules' => 
  array (
    'lang' => '_MODULES',
    'img' => 'modules.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
    'type' => '0',
  ),
  'money' => 
  array (
    'lang' => '_MONEY',
    'img' => 'money.png',
    'active' => '0',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
  ),
  'monitor' => 
  array (
    'lang' => '_MONITOR',
    'img' => 'monitor.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
    'type' => '0',
  ),
  'news' => 
  array (
    'lang' => '_NEWS',
    'img' => 'news.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
  ),
  'newsletter' => 
  array (
    'lang' => '_NEWSLETTER',
    'img' => 'newsletter.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
    'type' => '0',
  ),
  'order' => 
  array (
    'lang' => '_ORDER',
    'img' => 'order.png',
    'active' => '0',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
  ),
  'pages' => 
  array (
    'lang' => '_PAGES',
    'img' => 'pages.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
  ),
  'privat' => 
  array (
    'lang' => '_PRIVAT',
    'img' => 'privat.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
    'type' => '0',
  ),
  'ratings' => 
  array (
    'lang' => '_RATINGS',
    'img' => 'ratings.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
    'type' => '0',
  ),
  'recommend' => 
  array (
    'lang' => '_RECOMMEND',
    'img' => 'recommend.png',
    'active' => '1',
    'view' => '1',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
  ),
  'referers' => 
  array (
    'lang' => '_REFERERS',
    'img' => 'referers.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
    'type' => '0',
  ),
  'replace' => 
  array (
    'lang' => '_REPLACE',
    'img' => 'replace.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
    'type' => '0',
  ),
  'rss' => 
  array (
    'lang' => '_RSS',
    'img' => 'rss.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
    'type' => '0',
  ),
  'rss_info' => 
  array (
    'lang' => '_RSS_INFO',
    'img' => 'rss_info.png',
    'active' => '1',
    'view' => '1',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
  ),
  'search' => 
  array (
    'lang' => '_SEARCH',
    'img' => 'search.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
  ),
  'security' => 
  array (
    'lang' => '_SECURITY',
    'img' => 'security.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
    'type' => '0',
  ),
  'shop' => 
  array (
    'lang' => '_SHOP',
    'img' => 'shop.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
  ),
  'sitemap' => 
  array (
    'lang' => '_SITEMAP',
    'img' => 'sitemap.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '2',
    'top' => '0',
  ),
  'statistic' => 
  array (
    'lang' => '_STATISTIC',
    'img' => 'statistic.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
    'type' => '0',
  ),
  'template' => 
  array (
    'lang' => '_TEMPLATE',
    'img' => 'template.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
    'type' => '0',
  ),
  'uploads' => 
  array (
    'lang' => '_UPLOADS',
    'img' => 'uploads.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
    'type' => '0',
  ),
  'users' => 
  array (
    'lang' => '_USERS',
    'img' => 'users.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
  ),
  'voting' => 
  array (
    'lang' => '_VOTING',
    'img' => 'voting.png',
    'active' => '1',
    'view' => '0',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
  ),
  'whois' => 
  array (
    'lang' => '_WHOIS',
    'img' => 'whois.png',
    'active' => '1',
    'view' => '1',
    'menu' => '1',
    'group' => '0',
    'side' => '0',
    'top' => '0',
  ),
);
