<?php
# Author: Eduard Laas
# 2005 - 2026 SLAED
# License: MIT
# Website: slaed.net

# Data of the presentation module: dictionary fields name _PRES_* constants, proper names and quotes are raw text
return [
    'presentation' => [
        'sites' => [
            'akveduk.com.jpg' => ['name' => 'Акведук+', 'cat' => '_PRES_CAT_COMPANY'],
            'aquafanat.com.ua.jpg' => ['name' => 'Aquafanat', 'cat' => '_PRES_CAT_PORTAL'],
            'avtogps.com.gif' => ['name' => 'GPS Навигация', 'cat' => '_PRES_CAT_TECH'],
            'avtoprof.ru.jpg' => ['name' => 'Автошкола СтильАвто', 'cat' => '_PRES_CAT_EDU'],
            'avtozvuk-ua.com.gif' => ['name' => 'Kleo', 'cat' => '_PRES_CAT_SHOP'],
            'best-les.com.gif' => ['name' => 'Best-Les', 'cat' => '_PRES_CAT_BUILD'],
            'blagotvor.ru.jpg' => ['name' => 'Храм Преображения Господня', 'cat' => '_PRES_CAT_RELIGION'],
            'bloshiha.ru.jpg' => ['name' => 'Моя родная Балашиха', 'cat' => '_PRES_CAT_CITY'],
            'brandpedia.ru.jpg' => ['name' => 'Brandpedia', 'cat' => '_PRES_CAT_ADS'],
            'cms-guru.ru.jpg' => ['name' => 'CMS Guru', 'cat' => '_PRES_CAT_FORUM'],
            'colabus.ru.gif' => ['name' => 'Colabus', 'cat' => '_PRES_CAT_PORTAL'],
            'colabus_0.ru.gif' => ['name' => 'Colabus', 'cat' => '_PRES_CAT_PORTAL'],
            'counterstrike.ru.jpg' => ['name' => 'Мир Counter-Strike', 'cat' => '_PRES_CAT_GAMES'],
            'd-e-d.biz.gif' => ['name' => 'Dreamlike Event Decoration', 'cat' => '_PRES_CAT_DESIGN'],
            'delo-novoe.ru.gif' => ['name' => 'Дело Новое', 'cat' => '_PRES_CAT_SOFT'],
            'domsexa.com.jpg' => ['name' => 'ДомСекса', 'cat' => '_PRES_CAT_FUN'],
            'dvijlo.com.gif' => ['name' => 'Dvijlo', 'cat' => '_PRES_CAT_PORTAL'],
            'egomel.info.jpg' => ['name' => 'Гомель Онлайн', 'cat' => '_PRES_CAT_CITY'],
            'ermakov-sv.ru.gif' => ['name' => 'Глава Енисейского района', 'cat' => '_PRES_CAT_PERSONAL'],
            'europeisky63.ru.jpg' => ['name' => 'Европейский', 'cat' => '_PRES_CAT_FOOD'],
            'feldsher.ru.gif' => ['name' => 'Feldsher', 'cat' => '_PRES_CAT_FORUM'],
            'fomina.info.jpg' => ['name' => 'Валентина Фомина', 'cat' => '_PRES_CAT_PERSONAL'],
            'goncharoff.biz.jpg' => ['name' => 'Goncharoff', 'cat' => '_PRES_CAT_BLOG'],
            'hayfilm.info.gif' => ['name' => 'HayFilm Studio', 'cat' => '_PRES_CAT_MUSIC'],
            'hostmind.ru.png' => ['name' => 'HostMind', 'cat' => '_PRES_CAT_HOSTING'],
            'integra-light.ru.jpg' => ['name' => 'Интегра Лайт', 'cat' => '_PRES_CAT_BUILD'],
            'itbeton.ru.jpg' => ['name' => 'ИТ Бетон', 'cat' => '_PRES_CAT_INDUSTRY'],
            'jeep-servis.rf.jpg' => ['name' => 'Jeep-Сервис', 'cat' => '_PRES_CAT_AUTO'],
            'karnavalbelya.ru.jpg' => ['name' => 'Карнавал Белья', 'cat' => '_PRES_CAT_SHOP'],
            'keyelement.ru.gif' => ['name' => 'Ключевой Элемент', 'cat' => '_PRES_CAT_SOFT'],
            'livetver.ru.gif' => ['name' => 'Живая Тверь', 'cat' => '_PRES_CAT_CITY'],
            'livetver_0.ru.gif' => ['name' => 'Живая Тверь', 'cat' => '_PRES_CAT_CITY'],
            'lvivgaz.lviv.ua.jpg' => ['name' => 'Львівгаз', 'cat' => '_PRES_CAT_COMPANY'],
            'markprior.ru.gif' => ['name' => 'MarkPrior', 'cat' => '_PRES_CAT_LAW'],
            'mayolica.ru.gif' => ['name' => 'Mayolica', 'cat' => '_PRES_CAT_DESIGN'],
            'mdk.su.gif' => ['name' => 'Максимально доступный каталог', 'cat' => '_PRES_CAT_CATALOG'],
            'mediacms.net.jpg' => ['name' => 'Media CMS', 'cat' => '_PRES_CAT_SOFT'],
            'mkkprf.ru.jpg' => ['name' => 'КПРФ Подмосковья', 'cat' => '_PRES_CAT_POLITICS'],
            'molodrk.ru.jpg' => ['name' => 'Молодёжный портал Коми', 'cat' => '_PRES_CAT_PORTAL'],
            'moscow-index.ru.jpg' => ['name' => 'Московский Индекс', 'cat' => '_PRES_CAT_CITY'],
            'most-konsalt.ru.gif' => ['name' => 'МОСТ', 'cat' => '_PRES_CAT_COMPANY'],
            'movieshayfilm.com.gif' => ['name' => 'HayFilm Movies', 'cat' => '_PRES_CAT_CINEMA'],
            'mylove-you.ru.png' => ['name' => 'Признания в любви', 'cat' => '_PRES_CAT_FUN'],
            'myonly.ru.gif' => ['name' => 'MY Only', 'cat' => '_PRES_CAT_CATALOG'],
            'neftedebit.ru.gif' => ['name' => 'Нефтедебит', 'cat' => '_PRES_CAT_INDUSTRY'],
            'openseo.ru.jpg' => ['name' => 'OpenSeo', 'cat' => '_PRES_CAT_ADS'],
            'oslik.info.jpg' => ['name' => 'Oslik', 'cat' => '_PRES_CAT_FUN'],
            'ovochi.ru.gif' => ['name' => 'Вкусные Ovochi', 'cat' => '_PRES_CAT_BLOG'],
            'ovochi.ru.jpg' => ['name' => 'Овощи.ru', 'cat' => '_PRES_CAT_PORTAL'],
            'patriciakaas.ru.gif' => ['name' => 'Patricia Kaas', 'cat' => '_PRES_CAT_FANSITE'],
            'pe4ora.ru.jpg' => ['name' => 'Печора', 'cat' => '_PRES_CAT_CITY'],
            'pentagon.in.ua.jpg' => ['name' => 'Пентагон', 'cat' => '_PRES_CAT_CITY'],
            'planetoffshore.gif' => ['name' => 'Planet Offshore', 'cat' => '_PRES_CAT_SOCIAL'],
            'prizrakk.ru.jpg' => ['name' => 'Призрачный мир', 'cat' => '_PRES_CAT_FUN'],
            'prostootdam.ru.jpg' => ['name' => 'простоОтдам', 'cat' => '_PRES_CAT_NOTICES'],
            'ptenzial-plus.ru.jpg' => ['name' => 'Потенциал Плюс', 'cat' => '_PRES_CAT_BUILD'],
            'ra-tex.ru.gif' => ['name' => 'РА-текс', 'cat' => '_PRES_CAT_COMPANY'],
            'rusrap.org.jpg' => ['name' => 'RusRap', 'cat' => '_PRES_CAT_MUSIC'],
            'rustek.de.gif' => ['name' => 'Rustek', 'cat' => '_PRES_CAT_PORTAL'],
            'salavatcity.ru.jpg' => ['name' => 'Город Салават', 'cat' => '_PRES_CAT_CITY'],
            'setitagila.ru.jpg' => ['name' => 'СетиТагила', 'cat' => '_PRES_CAT_PROVIDER'],
            'start-drive.com.ua.gif' => ['name' => 'Start-Drive', 'cat' => '_PRES_CAT_AUTO'],
            'stepashka.com.gif' => ['name' => 'Степашка', 'cat' => '_PRES_CAT_CINEMA'],
            'supertema.ru.jpg' => ['name' => 'TEMA', 'cat' => '_PRES_CAT_ART'],
            'svarg.ru.gif' => ['name' => 'Сварог', 'cat' => '_PRES_CAT_COMPANY'],
            'tolma4.ru.gif' => ['name' => 'Tolma4', 'cat' => '_PRES_CAT_BUREAU'],
            'tonks.ru.jpg' => ['name' => 'Tonks', 'cat' => '_PRES_CAT_SOCIAL'],
            'toursnlodging.com.gif' => ['name' => 'Travel Operator', 'cat' => '_PRES_CAT_TRAVEL'],
            'userfaq.ru.gif' => ['name' => 'UserFAQ', 'cat' => '_PRES_CAT_FAQ'],
            'viselki.ru.jpg' => ['name' => 'Выселки.РФ', 'cat' => '_PRES_CAT_CITY'],
            'volentex.ru.jpg' => ['name' => 'Волентекс', 'cat' => '_PRES_CAT_SHOP'],
        ],
        'brand' => [
            'wallpaper_ease.png' => ['title' => '_PRES_EASE', 'group' => '_PRES_GRP_ADS', 'mark' => ''],
            'wallpaper_effectiveness.png' => ['title' => '_PRES_EFFECT', 'group' => '_PRES_GRP_ADS', 'mark' => ''],
            'wallpaper_functionality.png' => ['title' => '_PRES_FUNC', 'group' => '_PRES_GRP_ADS', 'mark' => ''],
            'wallpaper_security.png' => ['title' => '_PRES_SAFE', 'group' => '_PRES_GRP_ADS', 'mark' => ''],
            'wallpaper.png' => ['title' => '_PRES_BRAND_MOTTO', 'group' => '_PRES_GRP_ADS', 'mark' => ''],
            'background-1.png' => ['title' => '_PRES_BRAND_BG', 'group' => '_PRES_GRP_BG', 'mark' => '1'],
            'background-2.png' => ['title' => '_PRES_BRAND_BG', 'group' => '_PRES_GRP_BG', 'mark' => '2'],
            'background-3.png' => ['title' => '_PRES_BRAND_BG', 'group' => '_PRES_GRP_BG', 'mark' => '3'],
            'background-4.png' => ['title' => '_PRES_BRAND_BG', 'group' => '_PRES_GRP_BG', 'mark' => '4'],
            'background-5.png' => ['title' => '_PRES_BRAND_BG', 'group' => '_PRES_GRP_BG', 'mark' => '5'],
            'background-6.png' => ['title' => '_PRES_BRAND_BG', 'group' => '_PRES_GRP_BG', 'mark' => '6'],
            'background-7.png' => ['title' => '_PRES_BRAND_BG', 'group' => '_PRES_GRP_BG', 'mark' => '7'],
            'box.png' => ['title' => '_PRES_BRAND_BOX', 'group' => '_PRES_GRP_ADS', 'mark' => ''],
            'logotype-1.png' => ['title' => '_PRES_BRAND_LOGO', 'group' => '_PRES_GRP_LOGO', 'mark' => '1'],
            'logotype-2.png' => ['title' => '_PRES_BRAND_LOGO', 'group' => '_PRES_GRP_LOGO', 'mark' => '2'],
            'logotype-3.png' => ['title' => '_PRES_BRAND_LOGO', 'group' => '_PRES_GRP_LOGO', 'mark' => '3'],
            'logotype-4.png' => ['title' => '_PRES_BRAND_LOGO', 'group' => '_PRES_GRP_LOGO', 'mark' => '4'],
            'logotype-5.png' => ['title' => '_PRES_BRAND_LOGO', 'group' => '_PRES_GRP_LOGO', 'mark' => '5'],
            'logotype-6.png' => ['title' => '_PRES_BRAND_LOGO', 'group' => '_PRES_GRP_LOGO', 'mark' => '6'],
            'logotype-7.png' => ['title' => '_PRES_BRAND_LOGO', 'group' => '_PRES_GRP_LOGO', 'mark' => '7'],
            'logotype-8.png' => ['title' => '_PRES_BRAND_LOGO', 'group' => '_PRES_GRP_LOGO', 'mark' => '8'],
            'logotype-9.png' => ['title' => '_PRES_BRAND_LOGO', 'group' => '_PRES_GRP_LOGO', 'mark' => '9'],
            'partner_bronze.png' => ['title' => '_PRES_BRAND_BRONZE', 'group' => '_PRES_GRP_PARTNER', 'mark' => ''],
            'partner_client.png' => ['title' => '_PRES_BRAND_CLIENT', 'group' => '_PRES_GRP_PARTNER', 'mark' => ''],
            'partner_developer.png' => ['title' => '_PRES_BRAND_DEV', 'group' => '_PRES_GRP_PARTNER', 'mark' => ''],
            'partner_gold.png' => ['title' => '_PRES_BRAND_GOLD', 'group' => '_PRES_GRP_PARTNER', 'mark' => ''],
            'partner_hosting.png' => ['title' => '_PRES_BRAND_HOST', 'group' => '_PRES_GRP_PARTNER', 'mark' => ''],
            'partner_silver.png' => ['title' => '_PRES_BRAND_SILVER', 'group' => '_PRES_GRP_PARTNER', 'mark' => ''],
            'souvenir_cap.png' => ['title' => '_PRES_BRAND_CAP', 'group' => '_PRES_GRP_GIFTS', 'mark' => ''],
            'souvenir_flyer.png' => ['title' => '_PRES_BRAND_FLYER', 'group' => '_PRES_GRP_GIFTS', 'mark' => ''],
            'souvenir_handle.png' => ['title' => '_PRES_BRAND_PEN', 'group' => '_PRES_GRP_GIFTS', 'mark' => ''],
            'souvenir_lighter.png' => ['title' => '_PRES_BRAND_LIGHT', 'group' => '_PRES_GRP_GIFTS', 'mark' => ''],
            'souvenir_mug.png' => ['title' => '_PRES_BRAND_MUG', 'group' => '_PRES_GRP_GIFTS', 'mark' => ''],
            'souvenir_t-shirt.png' => ['title' => '_PRES_BRAND_SHIRT', 'group' => '_PRES_GRP_GIFTS', 'mark' => ''],
        ],
        'dna' => [
            'simplicity.webp' => ['title' => '_PRES_EASE', 'text' => '_PRES_EASE_A', 'more' => '_PRES_EASE_B', 'icon' => 'magic', 'href' => ''],
            'functionality.webp' => ['title' => '_PRES_FUNC', 'text' => '_PRES_FUNC_A', 'more' => '_PRES_FUNC_B', 'icon' => 'gear', 'href' => ''],
            'efficiency.webp' => ['title' => '_PRES_EFFECT', 'text' => '_PRES_EFFECT_A', 'more' => '_PRES_EFFECT_B', 'icon' => 'speedometer2', 'href' => ''],
            'security.webp' => ['title' => '_PRES_SAFE', 'text' => '_PRES_SAFE_A', 'more' => '_PRES_SAFE_B', 'icon' => 'shield-check', 'href' => ''],
        ],
        'voices' => [
            [
                'text' => 'Перенесли форум за один вечер: восемь лет тем, вложения, права доступа.'
                    .' Утром никто из пользователей не заметил переезда.',
                'name' => 'Андрей Кузьмин',
                'site' => 'avto-club.ru',
                'role' => '_PRES_ROLE_COMM',
                'since' => '2011',
                'tone' => 'primary',
                'marks' => [
                    ['icon' => 'chat-square-text', 'label' => '_FORUM'],
                    ['icon' => 'paperclip', 'label' => '_FILES'],
                    ['icon' => 'people', 'label' => '_USERS'],
                ],
            ],
            [
                'text' => 'Держим сорок разделов на обычном хостинге за 200 рублей.'
                    .' Кэш включён, страница собирается быстрее, чем приходит ответ от платёжного шлюза.',
                'name' => 'Марина Соловьёва',
                'site' => 'gorod-news.ru',
                'role' => '_PRES_ROLE_MEDIA',
                'since' => '2016',
                'tone' => 'success',
                'marks' => [
                    ['icon' => 'newspaper', 'label' => '_NEWS'],
                    ['icon' => 'lightning', 'label' => '_PRES_CACHE'],
                    ['icon' => 'bar-chart', 'label' => '_PRES_NAV_STATS'],
                ],
            ],
            [
                'text' => 'Свой модуль записи к мастеру написали за выходные, ядро трогать не пришлось.'
                    .' Обновления с тех пор ставим без правок.',
                'name' => 'Игорь Демченко',
                'site' => 'studio-remont.ru',
                'role' => '_PRES_ROLE_SERVICE',
                'since' => '2019',
                'tone' => 'accent',
                'marks' => [
                    ['icon' => 'boxes', 'label' => '_PRES_SP_N_MODULE'],
                    ['icon' => 'code-slash', 'label' => 'PHP'],
                    ['icon' => 'arrow-repeat', 'label' => '_PRES_MARK_UPGRADE'],
                ],
            ],
        ],
    ],
];
